/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class Add_Update_Pet extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Add_Update_Pet.class.getName());

    /**
     * Creates new form Add_Update_Pet
     */
    
private String currentImagePath = null;
    public Add_Update_Pet() {
        initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setupRadioButtons();
       
    }
    
    private void setupRadioButtons() {

        ButtonGroup houseTrainedGroup = new ButtonGroup();
        houseTrainedGroup.add(rb_Yes_HouseTrained);
        houseTrainedGroup.add(rb_No_HouseTrained);

        ButtonGroup spayedGroup = new ButtonGroup();
        spayedGroup.add(rb_Yes_Spayed);
        spayedGroup.add(rb_No_Spayed);

        ButtonGroup vaccinatedGroup = new ButtonGroup();
        vaccinatedGroup.add(rb_Yes_Vaccinated);
        vaccinatedGroup.add(rb_No_Vaccinated);

        ButtonGroup specialNeedsGroup = new ButtonGroup();
        specialNeedsGroup.add(rb_Yes_SpecialNeeds);
        specialNeedsGroup.add(rb_No_SpecialNeeds);
    }
    
    
    
    
    public void setPetImage(String path) {
        this.currentImagePath = path; 
        try {
            if (path != null && !path.isEmpty()) {
                ImageIcon icon = new ImageIcon(path);
                Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
                PetImg_AddUpdate.setIcon(new ImageIcon(img));
            }
        } catch (Exception e) {
            System.out.println("Image load error: " + e.getMessage());
        }
    }


    public String getCurrentImagePath() {
        return currentImagePath;
    }
    

    public void addImageUploadListener(java.awt.event.MouseListener listener) {
        PetImg_AddUpdate.addMouseListener(listener);
        PetImg_AddUpdate.setToolTipText("Click to upload image");
    }

    public javax.swing.JLabel getPetImgLabel() {
        return PetImg_AddUpdate;
    }
    
    
    public javax.swing.JTextField getTxtPetName() {
        return txtPetName_AddUpdate;
    }

     public javax.swing.JComboBox<String> getCbPetType() {
        return cbPetType_AU;
    }

    public javax.swing.JComboBox<String> getCbPetGender() {
        return cb_PetGender_AddUpdate;
    }

    public javax.swing.JComboBox<String> getCbPetAge() {
        return cb_PetAge_AddUpdate;
    }

    public javax.swing.JRadioButton getRbYesHouseTrained() {
        return rb_Yes_HouseTrained;
    }

    public javax.swing.JRadioButton getRbYesSpayed() {
        return rb_Yes_Spayed;
    }

    public javax.swing.JRadioButton getRbYesVaccinated() {
        return rb_Yes_Vaccinated;
    }

    public javax.swing.JRadioButton getRbYesSpecialNeeds() {
        return rb_Yes_SpecialNeeds;
    }
    
    public javax.swing.JRadioButton getRbNoHouseTrained() {
    return rb_No_HouseTrained;
}

    public javax.swing.JRadioButton getRbNoSpayed() {
        return rb_No_Spayed;
    }

    public javax.swing.JRadioButton getRbNoVaccinated() {
        return rb_No_Vaccinated;
    }

    public javax.swing.JRadioButton getRbNoSpecialNeeds() {
        return rb_No_SpecialNeeds;
    }
    
    // Action Listener fro Save and Exit Button
    public void addSavePetListener(ActionListener listener) {
        SaveAddUpdatePet.addActionListener(listener);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_Update_Panel = new javax.swing.JPanel();
        lblPetName_AU = new javax.swing.JLabel();
        lblPetType_AU = new javax.swing.JLabel();
        txtPetName_AddUpdate = new javax.swing.JTextField();
        lblPetGender_AU = new javax.swing.JLabel();
        lblPetAge_AU = new javax.swing.JLabel();
        lblHouseTrained = new javax.swing.JLabel();
        rb_Yes_HouseTrained = new javax.swing.JRadioButton();
        rb_No_HouseTrained = new javax.swing.JRadioButton();
        lblSpayed = new javax.swing.JLabel();
        rb_Yes_Spayed = new javax.swing.JRadioButton();
        rb_No_Spayed = new javax.swing.JRadioButton();
        lblVaccinated = new javax.swing.JLabel();
        rb_Yes_Vaccinated = new javax.swing.JRadioButton();
        rb_No_Vaccinated = new javax.swing.JRadioButton();
        lblSpecialNeeds = new javax.swing.JLabel();
        rb_Yes_SpecialNeeds = new javax.swing.JRadioButton();
        rb_No_SpecialNeeds = new javax.swing.JRadioButton();
        cb_PetGender_AddUpdate = new javax.swing.JComboBox<>();
        cb_PetAge_AddUpdate = new javax.swing.JComboBox<>();
        PetImg_AddUpdate = new javax.swing.JLabel();
        SaveAddUpdatePet = new javax.swing.JButton();
        lbl_AddUpdatePetDetail = new javax.swing.JLabel();
        cbPetType_AU = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Add_Update_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Add_Update_Panel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Add_Update_PanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblPetName_AU.setText("Pet Name:");

        lblPetType_AU.setText("Breed:");

        lblPetGender_AU.setText("Gender:");

        lblPetAge_AU.setText("Age:");

        lblHouseTrained.setText("House Trained:");

        rb_Yes_HouseTrained.setBackground(new java.awt.Color(255, 255, 255));
        rb_Yes_HouseTrained.setText("Yes");

        rb_No_HouseTrained.setBackground(new java.awt.Color(255, 255, 255));
        rb_No_HouseTrained.setText("No");

        lblSpayed.setText("Spayed/Neutered:");

        rb_Yes_Spayed.setBackground(new java.awt.Color(255, 255, 255));
        rb_Yes_Spayed.setText("Yes");

        rb_No_Spayed.setBackground(new java.awt.Color(255, 255, 255));
        rb_No_Spayed.setText("No");
        rb_No_Spayed.addActionListener(this::rb_No_SpayedActionPerformed);

        lblVaccinated.setText("Vaccinated:");

        rb_Yes_Vaccinated.setBackground(new java.awt.Color(255, 255, 255));
        rb_Yes_Vaccinated.setText("Yes");

        rb_No_Vaccinated.setBackground(new java.awt.Color(255, 255, 255));
        rb_No_Vaccinated.setText("No");

        lblSpecialNeeds.setText("Special Needs:");

        rb_Yes_SpecialNeeds.setBackground(new java.awt.Color(255, 255, 255));
        rb_Yes_SpecialNeeds.setText("Yes");

        rb_No_SpecialNeeds.setBackground(new java.awt.Color(255, 255, 255));
        rb_No_SpecialNeeds.setText("No");

        cb_PetGender_AddUpdate.setBackground(new java.awt.Color(255, 153, 51));
        cb_PetGender_AddUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        cb_PetAge_AddUpdate.setBackground(new java.awt.Color(255, 153, 51));
        cb_PetAge_AddUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Born (<1 Year)", "Young (1-3 Years)", "Adult (3-8 Years)", "Senior (>8 Year)" }));

        PetImg_AddUpdate.setBackground(new java.awt.Color(255, 255, 255));
        PetImg_AddUpdate.setText("petImg");
        PetImg_AddUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        SaveAddUpdatePet.setBackground(new java.awt.Color(255, 153, 51));
        SaveAddUpdatePet.setText("Save");

        lbl_AddUpdatePetDetail.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        lbl_AddUpdatePetDetail.setText("Pet Detail Form");

        cbPetType_AU.setBackground(new java.awt.Color(255, 153, 51));
        cbPetType_AU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat", "Bird", "Marine", "Others" }));

        javax.swing.GroupLayout Add_Update_PanelLayout = new javax.swing.GroupLayout(Add_Update_Panel);
        Add_Update_Panel.setLayout(Add_Update_PanelLayout);
        Add_Update_PanelLayout.setHorizontalGroup(
            Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_AddUpdatePetDetail)
                .addGap(409, 409, 409))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createSequentialGroup()
                        .addComponent(SaveAddUpdatePet)
                        .addGap(440, 440, 440))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createSequentialGroup()
                        .addComponent(PetImg_AddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(437, 437, 437))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createSequentialGroup()
                        .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Add_Update_PanelLayout.createSequentialGroup()
                                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(Add_Update_PanelLayout.createSequentialGroup()
                                            .addGap(111, 111, 111)
                                            .addComponent(lblPetAge_AU, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Add_Update_PanelLayout.createSequentialGroup()
                                            .addGap(103, 103, 103)
                                            .addComponent(lblPetType_AU, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(lblPetGender_AU, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_PetAge_AddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbPetType_AU, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_PetGender_AddUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(Add_Update_PanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lblPetName_AU, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPetName_AddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createSequentialGroup()
                                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Yes_HouseTrained)
                                    .addComponent(lblHouseTrained)
                                    .addComponent(rb_No_HouseTrained))
                                .addGap(94, 94, 94)
                                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Yes_Spayed)
                                    .addComponent(lblSpayed)
                                    .addComponent(rb_No_Spayed))
                                .addGap(101, 101, 101)
                                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Yes_Vaccinated)
                                    .addComponent(lblVaccinated)
                                    .addComponent(rb_No_Vaccinated))
                                .addGap(115, 115, 115)
                                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Yes_SpecialNeeds)
                                    .addComponent(lblSpecialNeeds)
                                    .addComponent(rb_No_SpecialNeeds))))
                        .addGap(168, 168, 168))))
        );
        Add_Update_PanelLayout.setVerticalGroup(
            Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_Update_PanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lbl_AddUpdatePetDetail)
                .addGap(42, 42, 42)
                .addComponent(PetImg_AddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetName_AU)
                    .addComponent(txtPetName_AddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetType_AU)
                    .addComponent(cbPetType_AU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetGender_AU)
                    .addComponent(cb_PetGender_AddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetAge_AU)
                    .addComponent(cb_PetAge_AddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(Add_Update_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Add_Update_PanelLayout.createSequentialGroup()
                        .addComponent(lblHouseTrained)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Yes_HouseTrained)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_No_HouseTrained))
                    .addGroup(Add_Update_PanelLayout.createSequentialGroup()
                        .addComponent(lblSpayed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Yes_Spayed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_No_Spayed))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_Update_PanelLayout.createSequentialGroup()
                        .addComponent(lblVaccinated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Yes_Vaccinated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_No_Vaccinated))
                    .addGroup(Add_Update_PanelLayout.createSequentialGroup()
                        .addComponent(lblSpecialNeeds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_Yes_SpecialNeeds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_No_SpecialNeeds)))
                .addGap(51, 51, 51)
                .addComponent(SaveAddUpdatePet)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Add_Update_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Add_Update_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_No_SpayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_No_SpayedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_No_SpayedActionPerformed

    private void Add_Update_PanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Add_Update_PanelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_Update_PanelAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Add_Update_Pet().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_Update_Panel;
    private javax.swing.JLabel PetImg_AddUpdate;
    private javax.swing.JButton SaveAddUpdatePet;
    private javax.swing.JComboBox<String> cbPetType_AU;
    private javax.swing.JComboBox<String> cb_PetAge_AddUpdate;
    private javax.swing.JComboBox<String> cb_PetGender_AddUpdate;
    private javax.swing.JLabel lblHouseTrained;
    private javax.swing.JLabel lblPetAge_AU;
    private javax.swing.JLabel lblPetGender_AU;
    private javax.swing.JLabel lblPetName_AU;
    private javax.swing.JLabel lblPetType_AU;
    private javax.swing.JLabel lblSpayed;
    private javax.swing.JLabel lblSpecialNeeds;
    private javax.swing.JLabel lblVaccinated;
    private javax.swing.JLabel lbl_AddUpdatePetDetail;
    private javax.swing.JRadioButton rb_No_HouseTrained;
    private javax.swing.JRadioButton rb_No_Spayed;
    private javax.swing.JRadioButton rb_No_SpecialNeeds;
    private javax.swing.JRadioButton rb_No_Vaccinated;
    private javax.swing.JRadioButton rb_Yes_HouseTrained;
    private javax.swing.JRadioButton rb_Yes_Spayed;
    private javax.swing.JRadioButton rb_Yes_SpecialNeeds;
    private javax.swing.JRadioButton rb_Yes_Vaccinated;
    private javax.swing.JTextField txtPetName_AddUpdate;
    // End of variables declaration//GEN-END:variables
}
