/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminAllAccountStatus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminAllAccountStatus.class.getName());

    /**
     * Creates new form AdminAllAccountStatus
     */
    public AdminAllAccountStatus() {
        initComponents();
    }
    
    public void addAllAccountsListener(ActionListener listener) {
        AllAccounts_btn.addActionListener(listener);
    }

    public void addReportsListener(ActionListener listener) {
        Reports_btn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    public void addUnfreezeRequestsListener(ActionListener listener) {
        UnfreezeRequests_btn.addActionListener(listener);
    }
    
    
    

    public DefaultTableModel getTableModel() {
        return (DefaultTableModel) AdminAllAccountsStatusTable.getModel();
    }
    
    public javax.swing.JTable getTable() {
        return AdminAllAccountsStatusTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_AllAccountsPanel = new javax.swing.JPanel();
        toppanel_viewpet_adopter = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Reports_btn = new javax.swing.JButton();
        AllAccounts_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        UnfreezeRequests_btn = new javax.swing.JButton();
        PanelWithAllAccountsTable = new javax.swing.JPanel();
        AllAccountsScrollPane = new javax.swing.JScrollPane();
        AdminAllAccountsStatusTable = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        Search_UserAccount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admin_AllAccountsPanel.setBackground(new java.awt.Color(255, 255, 255));

        toppanel_viewpet_adopter.setBackground(new java.awt.Color(255, 153, 51));
        toppanel_viewpet_adopter.setPreferredSize(new java.awt.Dimension(1000, 112));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        Reports_btn.setText("Reports");

        AllAccounts_btn.setBackground(new java.awt.Color(255, 204, 102));
        AllAccounts_btn.setText("All Accounts");

        Logout_btn.setText("Logout");

        UnfreezeRequests_btn.setText("Unfreeze Request");
        UnfreezeRequests_btn.addActionListener(this::UnfreezeRequests_btnActionPerformed);

        javax.swing.GroupLayout toppanel_viewpet_adopterLayout = new javax.swing.GroupLayout(toppanel_viewpet_adopter);
        toppanel_viewpet_adopter.setLayout(toppanel_viewpet_adopterLayout);
        toppanel_viewpet_adopterLayout.setHorizontalGroup(
            toppanel_viewpet_adopterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanel_viewpet_adopterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Logo)
                .addGap(108, 108, 108)
                .addComponent(AllAccounts_btn)
                .addGap(35, 35, 35)
                .addComponent(Reports_btn)
                .addGap(26, 26, 26)
                .addComponent(UnfreezeRequests_btn)
                .addGap(152, 152, 152)
                .addComponent(Logout_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toppanel_viewpet_adopterLayout.setVerticalGroup(
            toppanel_viewpet_adopterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanel_viewpet_adopterLayout.createSequentialGroup()
                .addGroup(toppanel_viewpet_adopterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toppanel_viewpet_adopterLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Logo))
                    .addGroup(toppanel_viewpet_adopterLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(toppanel_viewpet_adopterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Logout_btn)
                            .addComponent(Reports_btn)
                            .addComponent(AllAccounts_btn)
                            .addComponent(UnfreezeRequests_btn))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PanelWithAllAccountsTable.setBackground(new java.awt.Color(248, 230, 182));

        AdminAllAccountsStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Type", "Username", "Email", "Report Count", "Status"
            }
        ));
        AllAccountsScrollPane.setViewportView(AdminAllAccountsStatusTable);

        javax.swing.GroupLayout PanelWithAllAccountsTableLayout = new javax.swing.GroupLayout(PanelWithAllAccountsTable);
        PanelWithAllAccountsTable.setLayout(PanelWithAllAccountsTableLayout);
        PanelWithAllAccountsTableLayout.setHorizontalGroup(
            PanelWithAllAccountsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelWithAllAccountsTableLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AllAccountsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelWithAllAccountsTableLayout.setVerticalGroup(
            PanelWithAllAccountsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelWithAllAccountsTableLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AllAccountsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jComboBox2.setBackground(new java.awt.Color(255, 204, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Active", "Reported", "Disabled", " " }));

        Search_UserAccount.setForeground(new java.awt.Color(102, 102, 102));
        Search_UserAccount.setText("Provider Name, Email etc");
        Search_UserAccount.addActionListener(this::Search_UserAccountActionPerformed);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N

        javax.swing.GroupLayout Admin_AllAccountsPanelLayout = new javax.swing.GroupLayout(Admin_AllAccountsPanel);
        Admin_AllAccountsPanel.setLayout(Admin_AllAccountsPanelLayout);
        Admin_AllAccountsPanelLayout.setHorizontalGroup(
            Admin_AllAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toppanel_viewpet_adopter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Admin_AllAccountsPanelLayout.createSequentialGroup()
                .addGroup(Admin_AllAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Admin_AllAccountsPanelLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Admin_AllAccountsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PanelWithAllAccountsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Admin_AllAccountsPanelLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(Search_UserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Admin_AllAccountsPanelLayout.setVerticalGroup(
            Admin_AllAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Admin_AllAccountsPanelLayout.createSequentialGroup()
                .addComponent(toppanel_viewpet_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(Admin_AllAccountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_UserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(PanelWithAllAccountsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin_AllAccountsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin_AllAccountsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_UserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_UserAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_UserAccountActionPerformed

    private void UnfreezeRequests_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnfreezeRequests_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnfreezeRequests_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminAllAccountStatus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AdminAllAccountsStatusTable;
    private javax.swing.JPanel Admin_AllAccountsPanel;
    private javax.swing.JScrollPane AllAccountsScrollPane;
    private javax.swing.JButton AllAccounts_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JPanel PanelWithAllAccountsTable;
    private javax.swing.JButton Reports_btn;
    private javax.swing.JTextField Search_UserAccount;
    private javax.swing.JButton UnfreezeRequests_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel toppanel_viewpet_adopter;
    // End of variables declaration//GEN-END:variables
}
