/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author User
 */
public class AdminReportedAccountManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminReportedAccountManagement.class.getName());

    /**
     * Creates new form AdminReportedAccountManagement
     */
    public AdminReportedAccountManagement() {
        initComponents();
    }
    
    public void addAllAccountsListener(ActionListener listener) {
        AllAccounts_btn.addActionListener(listener);
    }

    public void addReportsListener(ActionListener listener) {
        Reports_btn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    public void addUnfreezeRequestsListener(ActionListener listener) {
        UnfreezeRequests_btn.addActionListener(listener);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorPanel1 = new javax.swing.JPanel();
        toppanel_viewpet_adopter = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        AllAccounts_btn = new javax.swing.JButton();
        Reports_btn = new javax.swing.JButton();
        UnfreezeRequests_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        SearchbarReport = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ColorPanel1.setBackground(new java.awt.Color(255, 255, 255));

        toppanel_viewpet_adopter.setBackground(new java.awt.Color(255, 153, 51));
        toppanel_viewpet_adopter.setPreferredSize(new java.awt.Dimension(1000, 112));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        AllAccounts_btn.setText("All Accounts");

        Reports_btn.setBackground(new java.awt.Color(255, 204, 51));
        Reports_btn.setText("Reports");
        Reports_btn.addActionListener(this::Reports_btnActionPerformed);

        UnfreezeRequests_btn.setText("Unfreeze Requests");
        UnfreezeRequests_btn.addActionListener(this::UnfreezeRequests_btnActionPerformed);

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(this::Logout_btnActionPerformed);

        javax.swing.GroupLayout toppanel_viewpet_adopterLayout = new javax.swing.GroupLayout(toppanel_viewpet_adopter);
        toppanel_viewpet_adopter.setLayout(toppanel_viewpet_adopterLayout);
        toppanel_viewpet_adopterLayout.setHorizontalGroup(
            toppanel_viewpet_adopterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanel_viewpet_adopterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Logo)
                .addGap(96, 96, 96)
                .addComponent(AllAccounts_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(Reports_btn)
                .addGap(58, 58, 58)
                .addComponent(UnfreezeRequests_btn)
                .addGap(148, 148, 148)
                .addComponent(Logout_btn)
                .addGap(171, 171, 171))
        );
        toppanel_viewpet_adopterLayout.setVerticalGroup(
            toppanel_viewpet_adopterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanel_viewpet_adopterLayout.createSequentialGroup()
                .addGroup(toppanel_viewpet_adopterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toppanel_viewpet_adopterLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(toppanel_viewpet_adopterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AllAccounts_btn)
                            .addComponent(Reports_btn)
                            .addComponent(UnfreezeRequests_btn)
                            .addComponent(Logout_btn)))
                    .addGroup(toppanel_viewpet_adopterLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Logo)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        SearchbarReport.setForeground(new java.awt.Color(102, 102, 102));
        SearchbarReport.setText("Adopter Name, Email etc");
        SearchbarReport.addActionListener(this::SearchbarReportActionPerformed);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout ColorPanel1Layout = new javax.swing.GroupLayout(ColorPanel1);
        ColorPanel1.setLayout(ColorPanel1Layout);
        ColorPanel1Layout.setHorizontalGroup(
            ColorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColorPanel1Layout.createSequentialGroup()
                .addGroup(ColorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toppanel_viewpet_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ColorPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(SearchbarReport, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ColorPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ColorPanel1Layout.setVerticalGroup(
            ColorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ColorPanel1Layout.createSequentialGroup()
                .addComponent(toppanel_viewpet_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(ColorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchbarReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchbarReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbarReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbarReportActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void Reports_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reports_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Reports_btnActionPerformed

    private void UnfreezeRequests_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnfreezeRequests_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnfreezeRequests_btnActionPerformed

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed

    }//GEN-LAST:event_Logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminReportedAccountManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllAccounts_btn;
    private javax.swing.JPanel ColorPanel1;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JButton Reports_btn;
    private javax.swing.JTextField SearchbarReport;
    private javax.swing.JButton UnfreezeRequests_btn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel toppanel_viewpet_adopter;
    // End of variables declaration//GEN-END:variables
}
