/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class Admin_ViewShelterDetail extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_ViewShelterDetail.class.getName());

    /**
     * Creates new form Admin_ViewShelterDetail
     */
    public Admin_ViewShelterDetail() {
        initComponents();
    }

    public void setShelterName(String name) {
        Shelter_name_adopterView_shelter_details.setText(name);
    }

    public void setPhone(String phone) {
        Phone_number_adopterView_shelter_details.setText(phone);
    }

    public void setEmail(String email) {
        Email_adopterView_shelter_details.setText(email);
    }

    public void setAddress(String address) {
        Address_adopterView_shelter_details.setText(address);
    }

    public void setShelterImage(javax.swing.ImageIcon icon) {
        Shelter_logo_adopterView_shelter_details.setIcon(icon);
        Shelter_logo_adopterView_shelter_details.setText("");
    }

    public javax.swing.JButton getAboutButton() {
        return About_shelter_adopterView_shelter_details1;
    }

    public javax.swing.JButton getAvailableButton() {
        return Available_Pets1;
    }

    public javax.swing.JButton getAdoptedButton() {
        return Adopted_Pets1;
    }

    public javax.swing.JButton getExitButton() {
        return Exit_adopterView_shelter_details;
    }

    public javax.swing.JPanel getRightContentPanel() {
        return RightContentPanel;
    }

    public javax.swing.JPanel getTopSmallPanel() {
        return Top_small_panal;
    }
    
    public javax.swing.JPanel getContentPanel() {
        return ScrollPanel_ShelterView1;
    }

    public javax.swing.JScrollPane getScrollPane() {
        return jScrollPane2;
    }
    
    public javax.swing.JPanel getMainPanel() {
        return AdminViewShlterDetail_MainPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminViewShlterDetail_MainPanel = new javax.swing.JPanel();
        Exit_adopterView_shelter_details = new javax.swing.JButton();
        Address_adopterView_shelter_details = new javax.swing.JLabel();
        Shelter_name_adopterView_shelter_details = new javax.swing.JLabel();
        Locationtext = new javax.swing.JLabel();
        Email_adopterView_shelter_details = new javax.swing.JLabel();
        Phone_number_adopterView_shelter_details = new javax.swing.JLabel();
        Shelter_logo_adopterView_shelter_details = new javax.swing.JLabel();
        Contactstext = new javax.swing.JLabel();
        RightContentPanel1 = new javax.swing.JPanel();
        Top_small_panal1 = new javax.swing.JPanel();
        About_shelter_adopterView_shelter_details1 = new javax.swing.JButton();
        Available_Pets1 = new javax.swing.JButton();
        Adopted_Pets1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ScrollPanel_ShelterView1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Exit_adopterView_shelter_details.setBackground(new java.awt.Color(255, 153, 0));
        Exit_adopterView_shelter_details.setText("Exit");

        Address_adopterView_shelter_details.setText("jLabel3");

        Shelter_name_adopterView_shelter_details.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Shelter_name_adopterView_shelter_details.setText("jLabel1");

        Locationtext.setText("Location:");

        Email_adopterView_shelter_details.setText("jLabel1");

        Phone_number_adopterView_shelter_details.setText("jLabel1");

        Shelter_logo_adopterView_shelter_details.setText("jLabel1");

        Contactstext.setText("Contacts:");

        RightContentPanel1.setBackground(new java.awt.Color(255, 255, 255));
        RightContentPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        RightContentPanel1.setPreferredSize(new java.awt.Dimension(500, 210));
        RightContentPanel1.setLayout(null);

        Top_small_panal1.setBackground(new java.awt.Color(255, 204, 102));
        Top_small_panal1.setPreferredSize(new java.awt.Dimension(498, 40));
        Top_small_panal1.setLayout(null);

        About_shelter_adopterView_shelter_details1.setText("About Shelter");
        Top_small_panal1.add(About_shelter_adopterView_shelter_details1);
        About_shelter_adopterView_shelter_details1.setBounds(50, 10, 120, 28);

        Available_Pets1.setText("Available Pets");
        Top_small_panal1.add(Available_Pets1);
        Available_Pets1.setBounds(210, 10, 120, 28);

        Adopted_Pets1.setText("Adopted Pets");
        Top_small_panal1.add(Adopted_Pets1);
        Adopted_Pets1.setBounds(370, 10, 120, 28);

        RightContentPanel1.add(Top_small_panal1);
        Top_small_panal1.setBounds(0, 0, 530, 50);

        ScrollPanel_ShelterView1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ScrollPanel_ShelterView1Layout = new javax.swing.GroupLayout(ScrollPanel_ShelterView1);
        ScrollPanel_ShelterView1.setLayout(ScrollPanel_ShelterView1Layout);
        ScrollPanel_ShelterView1Layout.setHorizontalGroup(
            ScrollPanel_ShelterView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        ScrollPanel_ShelterView1Layout.setVerticalGroup(
            ScrollPanel_ShelterView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(ScrollPanel_ShelterView1);

        RightContentPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 50, 530, 480);

        javax.swing.GroupLayout AdminViewShlterDetail_MainPanelLayout = new javax.swing.GroupLayout(AdminViewShlterDetail_MainPanel);
        AdminViewShlterDetail_MainPanel.setLayout(AdminViewShlterDetail_MainPanelLayout);
        AdminViewShlterDetail_MainPanelLayout.setHorizontalGroup(
            AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                .addGroup(AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Exit_adopterView_shelter_details)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                        .addGroup(AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Address_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(Shelter_logo_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(Shelter_name_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addComponent(RightContentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addGroup(AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Locationtext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Phone_number_adopterView_shelter_details, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Contactstext, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Email_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(648, Short.MAX_VALUE)))
        );
        AdminViewShlterDetail_MainPanelLayout.setVerticalGroup(
            AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(RightContentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Shelter_logo_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Shelter_name_adopterView_shelter_details))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Address_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(Exit_adopterView_shelter_details)
                .addGap(29, 29, 29))
            .addGroup(AdminViewShlterDetail_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminViewShlterDetail_MainPanelLayout.createSequentialGroup()
                    .addGap(160, 160, 160)
                    .addComponent(Contactstext)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Phone_number_adopterView_shelter_details)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Email_adopterView_shelter_details)
                    .addGap(45, 45, 45)
                    .addComponent(Locationtext)
                    .addContainerGap(257, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminViewShlterDetail_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminViewShlterDetail_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_ViewShelterDetail().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_shelter_adopterView_shelter_details;
    private javax.swing.JButton About_shelter_adopterView_shelter_details1;
    private javax.swing.JLabel Address_adopterView_shelter_details;
    private javax.swing.JPanel AdminViewShlterDetail_MainPanel;
    private javax.swing.JButton Adopted_Pets;
    private javax.swing.JButton Adopted_Pets1;
    private javax.swing.JButton Available_Pets;
    private javax.swing.JButton Available_Pets1;
    private javax.swing.JLabel Contactstext;
    private javax.swing.JLabel Email_adopterView_shelter_details;
    private javax.swing.JButton Exit_adopterView_shelter_details;
    private javax.swing.JLabel Locationtext;
    private javax.swing.JLabel Phone_number_adopterView_shelter_details;
    private javax.swing.JPanel RightContentPanel;
    private javax.swing.JPanel RightContentPanel1;
    private javax.swing.JPanel ScrollPanel_ShelterView;
    private javax.swing.JPanel ScrollPanel_ShelterView1;
    private javax.swing.JLabel Shelter_logo_adopterView_shelter_details;
    private javax.swing.JLabel Shelter_name_adopterView_shelter_details;
    private javax.swing.JPanel Top_small_panal;
    private javax.swing.JPanel Top_small_panal1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
