/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell
 */
public class AdminReportedProvidersHandleBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminReportedProvidersHandleBoardPanel
     */
    public AdminReportedProvidersHandleBoardPanel() {
        initComponents();
    }
    
    
    public javax.swing.JTable getAdminReportsHandleTable() {
    return AdminReportsHandleTable;
}
    
    // ───── Shelter Info Setters ─────

    public void setShelterName(String name) {
        Shelter_name_shelterinfopanal_petview_adopter.setText(name);
    }

    public void setShelterEmail(String email) {
        ShelterMail_shelterinfopanal_petview_adopter.setText(email);
    }

    public void setShelterPhone(String phone) {
        ShelterPhonenumber_shelterinfopanal_petview_adopter.setText(phone);
    }

    public void setTotalReportCount(int count) {
        TotalReportedProvidersCount.setText(String.valueOf(count));
    }
    
    public void addViewShelterListener(ActionListener listener) {
        viewShelter_btn.addActionListener(listener);
    }

    public void setShelterLogo(ImageIcon icon) {
        Shelter_logo_shelterinfopanal_petview_adopter.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AdminReportsHandleTable = new javax.swing.JTable();
        Shelter_name_shelterinfopanal_petview_adopter = new javax.swing.JLabel();
        ShelterPhonenumber_shelterinfopanal_petview_adopter = new javax.swing.JLabel();
        ShelterMail_shelterinfopanal_petview_adopter = new javax.swing.JLabel();
        phoneicon_shelterinfopanal_petview_adopter = new javax.swing.JLabel();
        Mailicon_shelterinfopanal_petview_adopter = new javax.swing.JLabel();
        Shelter_logo_shelterinfopanal_petview_adopter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TotalReportedProvidersCount = new javax.swing.JLabel();
        viewShelter_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 230, 182));

        AdminReportsHandleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adopter Username", "Email", "Report Reason", "Status", "Action"
            }
        ));
        jScrollPane1.setViewportView(AdminReportsHandleTable);

        Shelter_name_shelterinfopanal_petview_adopter.setText("jLabel2");

        ShelterPhonenumber_shelterinfopanal_petview_adopter.setText("jLabel2");

        ShelterMail_shelterinfopanal_petview_adopter.setText("jLabel3");

        phoneicon_shelterinfopanal_petview_adopter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phone.png"))); // NOI18N

        Mailicon_shelterinfopanal_petview_adopter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mail-outline-rounded.png"))); // NOI18N

        Shelter_logo_shelterinfopanal_petview_adopter.setText("Shelter logo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("--------------- Reports --------------");

        jLabel2.setText("Total Reported Providers:");

        TotalReportedProvidersCount.setText("3");

        viewShelter_btn.setText("view shelter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Shelter_logo_shelterinfopanal_petview_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneicon_shelterinfopanal_petview_adopter)
                                    .addComponent(Mailicon_shelterinfopanal_petview_adopter))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ShelterMail_shelterinfopanal_petview_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ShelterPhonenumber_shelterinfopanal_petview_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(viewShelter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(Shelter_name_shelterinfopanal_petview_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalReportedProvidersCount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(344, 344, 344))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Shelter_logo_shelterinfopanal_petview_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Shelter_name_shelterinfopanal_petview_adopter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneicon_shelterinfopanal_petview_adopter)
                                    .addComponent(ShelterPhonenumber_shelterinfopanal_petview_adopter)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewShelter_btn)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShelterMail_shelterinfopanal_petview_adopter)
                            .addComponent(Mailicon_shelterinfopanal_petview_adopter))))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TotalReportedProvidersCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AdminReportsHandleTable;
    private javax.swing.JLabel Mailicon_shelterinfopanal_petview_adopter;
    private javax.swing.JLabel ShelterMail_shelterinfopanal_petview_adopter;
    private javax.swing.JLabel ShelterPhonenumber_shelterinfopanal_petview_adopter;
    private javax.swing.JLabel Shelter_logo_shelterinfopanal_petview_adopter;
    private javax.swing.JLabel Shelter_name_shelterinfopanal_petview_adopter;
    private javax.swing.JLabel TotalReportedProvidersCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel phoneicon_shelterinfopanal_petview_adopter;
    private javax.swing.JButton viewShelter_btn;
    // End of variables declaration//GEN-END:variables
}
