/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JTable;

/**
 *
 * @author OMEN
 */
public class AdminUnfreezeRequestManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminUnfreezeRequestManagement.class.getName());

    /**
     * Creates new form Admin_unfreez_account_request
     */
    public AdminUnfreezeRequestManagement() {
    initComponents();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        mainpanal = new javax.swing.JPanel();
        toppanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Logout_btn = new javax.swing.JButton();
        UnfreezeRequests_btn = new javax.swing.JButton();
        Reports_btn = new javax.swing.JButton();
        AllAccounts_btn = new javax.swing.JButton();
        Searchbar = new javax.swing.JTextField();
        SearchLogo = new javax.swing.JButton();
        Status = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        PetRequestsTable_ScrollPane = new javax.swing.JScrollPane();
        PetRequests_Table = new javax.swing.JTable();
        total_number_of_pets = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpanal.setBackground(new java.awt.Color(255, 255, 255));
        mainpanal.setPreferredSize(new java.awt.Dimension(988, 550));

        toppanel.setBackground(new java.awt.Color(255, 153, 51));
        toppanel.setPreferredSize(new java.awt.Dimension(1000, 112));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        Logout_btn.setText("Logout");

        UnfreezeRequests_btn.setBackground(new java.awt.Color(255, 204, 51));
        UnfreezeRequests_btn.setText("Unfreeze Request");
        UnfreezeRequests_btn.addActionListener(this::UnfreezeRequests_btnActionPerformed);

        Reports_btn.setText("Reports");

        AllAccounts_btn.setText("All Accounts");

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(AllAccounts_btn)
                .addGap(35, 35, 35)
                .addComponent(Reports_btn)
                .addGap(26, 26, 26)
                .addComponent(UnfreezeRequests_btn)
                .addGap(152, 152, 152)
                .addComponent(Logout_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(17, 17, 17))
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout_btn)
                    .addComponent(Reports_btn)
                    .addComponent(AllAccounts_btn)
                    .addComponent(UnfreezeRequests_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Searchbar.setForeground(new java.awt.Color(204, 204, 204));
        Searchbar.setText("provider name, email");
        Searchbar.addActionListener(this::SearchbarActionPerformed);

        SearchLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N

        Status.setBackground(new java.awt.Color(255, 190, 86));
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "pending", " " }));

        jLabel1.setText("Total Provider:");

        PetRequests_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "reportID", "providerID", "Provider Name", "Email", "Report", "Request Details", "Status", "Action"
            }
        ));
        PetRequestsTable_ScrollPane.setViewportView(PetRequests_Table);
        if (PetRequests_Table.getColumnModel().getColumnCount() > 0) {
            PetRequests_Table.getColumnModel().getColumn(3).setPreferredWidth(200);
            PetRequests_Table.getColumnModel().getColumn(3).setMaxWidth(1000);
            PetRequests_Table.getColumnModel().getColumn(4).setPreferredWidth(2);
        }

        total_number_of_pets.setText("jLabel2");

        javax.swing.GroupLayout mainpanalLayout = new javax.swing.GroupLayout(mainpanal);
        mainpanal.setLayout(mainpanalLayout);
        mainpanalLayout.setHorizontalGroup(
            mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainpanalLayout.createSequentialGroup()
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PetRequestsTable_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainpanalLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_number_of_pets, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainpanalLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainpanalLayout.createSequentialGroup()
                                .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainpanalLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        mainpanalLayout.setVerticalGroup(
            mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanalLayout.createSequentialGroup()
                .addComponent(toppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(total_number_of_pets))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PetRequestsTable_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanal, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanal, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbarActionPerformed

    private void UnfreezeRequests_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnfreezeRequests_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnfreezeRequests_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllAccounts_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JScrollPane PetRequestsTable_ScrollPane;
    private javax.swing.JTable PetRequests_Table;
    private javax.swing.JButton Reports_btn;
    private javax.swing.JButton SearchLogo;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JButton UnfreezeRequests_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainpanal;
    private javax.swing.JPanel toppanel;
    private javax.swing.JLabel total_number_of_pets;
    // End of variables declaration//GEN-END:variables


public javax.swing.JTable getPetRequestsTable() {
    return PetRequests_Table;
}

public void setTotalProviders(String count) {
    total_number_of_pets.setText(count);
}

 

public void addAllAccountsListener(ActionListener listener) {
        AllAccounts_btn.addActionListener(listener);
    }

    public void addReportsListener(ActionListener listener) {
        Reports_btn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    public void addUnfreezeRequestsListener(ActionListener listener) {
        UnfreezeRequests_btn.addActionListener(listener);
    }

   
}
