/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class AdopterPetFavouriteCard extends javax.swing.JPanel {

    /**
     * Creates new form AdopterPetFavouriteCard
     */
    public AdopterPetFavouriteCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderRequestCard = new javax.swing.JLabel();
        AgeRequestCard = new javax.swing.JLabel();
        LblRequestCardPetBreed = new javax.swing.JLabel();
        LblRequestCardPetGender = new javax.swing.JLabel();
        LblRequestCardPetAge = new javax.swing.JLabel();
        PetFav_ViewMoreBtn = new javax.swing.JButton();
        LblRequestCardPetName = new javax.swing.JLabel();
        PetFav_RemoveBtn = new javax.swing.JButton();
        PetImgRequestCard = new javax.swing.JLabel();
        BreedRequestCard = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 230, 182));

        GenderRequestCard.setText("Gender:");

        AgeRequestCard.setText("Age:");

        LblRequestCardPetBreed.setText("Pet Breed");

        LblRequestCardPetGender.setText("Pet Gender");

        LblRequestCardPetAge.setText("jLabel7");

        PetFav_ViewMoreBtn.setText("View More");

        LblRequestCardPetName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblRequestCardPetName.setText("Jonny");

        PetFav_RemoveBtn.setText("Remove");
        PetFav_RemoveBtn.addActionListener(this::PetFav_RemoveBtnActionPerformed);

        PetImgRequestCard.setText("jLabel4");

        BreedRequestCard.setText("Breed:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(PetImgRequestCard, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgeRequestCard)
                    .addComponent(GenderRequestCard)
                    .addComponent(BreedRequestCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblRequestCardPetBreed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblRequestCardPetGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblRequestCardPetAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PetFav_ViewMoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PetFav_RemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(LblRequestCardPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BreedRequestCard)
                            .addComponent(LblRequestCardPetBreed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenderRequestCard)
                            .addComponent(LblRequestCardPetGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeRequestCard)
                            .addComponent(LblRequestCardPetAge)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(PetImgRequestCard, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(PetFav_ViewMoreBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PetFav_RemoveBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(LblRequestCardPetName)
                    .addContainerGap(114, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PetFav_RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetFav_RemoveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetFav_RemoveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeRequestCard;
    private javax.swing.JLabel BreedRequestCard;
    private javax.swing.JLabel GenderRequestCard;
    private javax.swing.JLabel LblRequestCardPetAge;
    private javax.swing.JLabel LblRequestCardPetBreed;
    private javax.swing.JLabel LblRequestCardPetGender;
    private javax.swing.JLabel LblRequestCardPetName;
    private javax.swing.JButton PetFav_RemoveBtn;
    private javax.swing.JButton PetFav_ViewMoreBtn;
    private javax.swing.JLabel PetImgRequestCard;
    // End of variables declaration//GEN-END:variables
}
