/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.ProviderData;





/**
 *
 * @author OMEN
 */
public class AdopterView_Shelter_Detail extends javax.swing.JFrame {
   
  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdopterView_Shelter_Detail.class.getName());

    /**
     * Creates new form AdopterView_Shelter_Detail
     */
    
    public AdopterView_Shelter_Detail(ProviderData provider, JFrame parentFrame) {
        initComponents();
        new Controller.ShelterDetailController(this, provider, parentFrame);
        new Controller.NavigationController(this);
    }

    public void setShelterName(String name) {
        Shelter_name_adopterView_shelter_details.setText(name);
    }

    public void setPhone(String phone) {
        Phone_number_adopterView_shelter_details.setText(phone);
    }

    public void setEmail(String email) {
        Email_adopterView_shelter_details.setText(email);
    }

    public void setAddress(String address) {
        Address_adopterView_shelter_details.setText(address);
    }

    public void setShelterImage(javax.swing.ImageIcon icon) {
        Shelter_logo_adopterView_shelter_details.setIcon(icon);
        Shelter_logo_adopterView_shelter_details.setText("");
    }

    public javax.swing.JButton getAboutButton() {
        return About_shelter_adopterView_shelter_details;
    }

    public javax.swing.JButton getAvailableButton() {
        return Available_Pets;
    }

    public javax.swing.JButton getAdoptedButton() {
        return Adopted_Pets;
    }

    public javax.swing.JButton getExitButton() {
        return Exit_adopterView_shelter_details;
    }

    public javax.swing.JPanel getRightContentPanel() {
        return RightContentPanel;
    }

    public javax.swing.JPanel getTopSmallPanel() {
        return Top_small_panal;
    }

    public void addHomeListener(ActionListener listener) {
        Home_btn.addActionListener(listener);
    }

    public void addMyRequestsListener(ActionListener listener) {
        MyRequests_btn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    public void addShelterListener(ActionListener listener) {
        Shelters_btn.addActionListener(listener);
    }

    public javax.swing.JButton getHomeButton() {
        return Home_btn;
    }

    public javax.swing.JButton getMyRequestsButton() {
        return MyRequests_btn;
    }

    public javax.swing.JButton getLogoutButton() {
        return Logout_btn;
    }

    public javax.swing.JButton getSheltersButton() {
        return Shelters_btn;
    }



/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanal = new javax.swing.JPanel();
        toppanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Home_btn = new javax.swing.JButton();
        MyRequests_btn = new javax.swing.JButton();
        Shelters_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        Favourite_btn = new javax.swing.JButton();
        Favourite_text = new javax.swing.JLabel();
        profile_btn = new javax.swing.JButton();
        Profile_text = new javax.swing.JLabel();
        Shelter_logo_adopterView_shelter_details = new javax.swing.JLabel();
        Shelter_name_adopterView_shelter_details = new javax.swing.JLabel();
        Contactstext = new javax.swing.JLabel();
        Phone_number_adopterView_shelter_details = new javax.swing.JLabel();
        Email_adopterView_shelter_details = new javax.swing.JLabel();
        Locationtext = new javax.swing.JLabel();
        Address_adopterView_shelter_details = new javax.swing.JLabel();
        Exit_adopterView_shelter_details = new javax.swing.JButton();
        RightContentPanel = new javax.swing.JPanel();
        Top_small_panal = new javax.swing.JPanel();
        About_shelter_adopterView_shelter_details = new javax.swing.JButton();
        Available_Pets = new javax.swing.JButton();
        Adopted_Pets = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        toppanel.setBackground(new java.awt.Color(255, 153, 51));
        toppanel.setPreferredSize(new java.awt.Dimension(1000, 112));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        Home_btn.setText("Home");

        MyRequests_btn.setText("My Requests");

        Shelters_btn.setBackground(new java.awt.Color(255, 204, 51));
        Shelters_btn.setText("Shelters");

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(this::Logout_btnActionPerformed);

        Favourite_btn.setBackground(new java.awt.Color(255, 153, 51));
        Favourite_btn.setForeground(new java.awt.Color(255, 153, 51));
        Favourite_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/petFavBtnIcon.png"))); // NOI18N
        Favourite_btn.setBorder(null);
        Favourite_btn.addActionListener(this::Favourite_btnActionPerformed);

        Favourite_text.setText("Favourite");

        profile_btn.setBackground(new java.awt.Color(255, 153, 51));
        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileButtonIcon.png"))); // NOI18N
        profile_btn.setBorder(null);
        profile_btn.addActionListener(this::profile_btnActionPerformed);

        Profile_text.setText("profile");

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(Home_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MyRequests_btn)
                .addGap(18, 18, 18)
                .addComponent(Shelters_btn)
                .addGap(18, 18, 18)
                .addComponent(Logout_btn)
                .addGap(23, 23, 23)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toppanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(Favourite_btn))
                    .addGroup(toppanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Favourite_text)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_btn)
                    .addComponent(Profile_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Favourite_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_btn)
                    .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Home_btn)
                        .addComponent(MyRequests_btn)
                        .addComponent(Shelters_btn)
                        .addComponent(Logout_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Favourite_text)
                    .addComponent(Profile_text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(17, 17, 17))
        );

        Shelter_logo_adopterView_shelter_details.setText("jLabel1");

        Shelter_name_adopterView_shelter_details.setText("jLabel1");

        Contactstext.setText("Contacts:");

        Phone_number_adopterView_shelter_details.setText("jLabel1");

        Email_adopterView_shelter_details.setText("jLabel1");

        Locationtext.setText("Location:");

        Address_adopterView_shelter_details.setText("jLabel3");

        Exit_adopterView_shelter_details.setBackground(new java.awt.Color(255, 153, 0));
        Exit_adopterView_shelter_details.setText("Exit");

        RightContentPanel.setBackground(new java.awt.Color(248, 230, 182));
        RightContentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RightContentPanel.setPreferredSize(new java.awt.Dimension(500, 210));
        RightContentPanel.setLayout(null);

        Top_small_panal.setBackground(new java.awt.Color(255, 204, 102));
        Top_small_panal.setPreferredSize(new java.awt.Dimension(498, 40));
        Top_small_panal.setLayout(null);

        About_shelter_adopterView_shelter_details.setText("About Shelter");
        Top_small_panal.add(About_shelter_adopterView_shelter_details);
        About_shelter_adopterView_shelter_details.setBounds(50, 10, 120, 28);

        Available_Pets.setText("Available Pets");
        Top_small_panal.add(Available_Pets);
        Available_Pets.setBounds(210, 10, 120, 28);

        Adopted_Pets.setText("Adopted Pets");
        Top_small_panal.add(Adopted_Pets);
        Adopted_Pets.setBounds(370, 10, 120, 28);

        RightContentPanel.add(Top_small_panal);
        Top_small_panal.setBounds(0, 0, 530, 40);

        javax.swing.GroupLayout mainpanalLayout = new javax.swing.GroupLayout(mainpanal);
        mainpanal.setLayout(mainpanalLayout);
        mainpanalLayout.setHorizontalGroup(
            mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanalLayout.createSequentialGroup()
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanalLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Shelter_logo_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Locationtext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(Email_adopterView_shelter_details, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Phone_number_adopterView_shelter_details, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Address_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Contactstext, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Shelter_name_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainpanalLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Exit_adopterView_shelter_details)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RightContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(toppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainpanalLayout.setVerticalGroup(
            mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanalLayout.createSequentialGroup()
                .addComponent(toppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanalLayout.createSequentialGroup()
                        .addGroup(mainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Shelter_logo_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Shelter_name_adopterView_shelter_details))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Contactstext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Phone_number_adopterView_shelter_details)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Email_adopterView_shelter_details)
                        .addGap(45, 45, 45)
                        .addComponent(Locationtext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Address_adopterView_shelter_details, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(Exit_adopterView_shelter_details)
                        .addGap(36, 36, 36))
                    .addGroup(mainpanalLayout.createSequentialGroup()
                        .addComponent(RightContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed

    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Favourite_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Favourite_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Favourite_btnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_btnActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_shelter_adopterView_shelter_details;
    private javax.swing.JLabel Address_adopterView_shelter_details;
    private javax.swing.JButton Adopted_Pets;
    private javax.swing.JButton Available_Pets;
    private javax.swing.JLabel Contactstext;
    private javax.swing.JLabel Email_adopterView_shelter_details;
    private javax.swing.JButton Exit_adopterView_shelter_details;
    private javax.swing.JButton Favourite_btn;
    private javax.swing.JLabel Favourite_text;
    private javax.swing.JButton Home_btn;
    private javax.swing.JLabel Locationtext;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JButton MyRequests_btn;
    private javax.swing.JLabel Phone_number_adopterView_shelter_details;
    private javax.swing.JLabel Profile_text;
    private javax.swing.JPanel RightContentPanel;
    private javax.swing.JLabel Shelter_logo_adopterView_shelter_details;
    private javax.swing.JLabel Shelter_name_adopterView_shelter_details;
    private javax.swing.JButton Shelters_btn;
    private javax.swing.JPanel Top_small_panal;
    private javax.swing.JPanel mainpanal;
    private javax.swing.JButton profile_btn;
    private javax.swing.JPanel toppanel;
    // End of variables declaration//GEN-END:variables

    

    

    
    

    
}
