/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.NavigationController;
import Controller.AdoptionRequestController;
import java.awt.event.ActionListener;


/**
 *
 * @author User
 */
public class AdoptionRequestTrackingPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdoptionRequestTrackingPage.class.getName());

    /**
     * Creates new form AdoptionHistory
     */
    
    public AdoptionRequestTrackingPage() {
        initComponents();
        setLocationRelativeTo(null);
        new NavigationController(this); 
        
        new AdoptionRequestController(this);
    }
    
    //   GETTERS
    public javax.swing.JPanel getRequestContainerPanel() {
        return requestContainerPanel;
    }

    public javax.swing.JScrollPane getAdopterAdoptionRequestsScroll() {
        return AdopterAdoptionRequestsScroll;
    }

    public javax.swing.JLabel getAdopterTotalRequestsCount() {
        return AdopterTotalRequestsCount;
    }
    
    
    // LISTENERS
    public void addHomeListener(ActionListener listener) {
        Home_btn.addActionListener(listener);
    }

    public void addMyRequestsListener(ActionListener listener) {
        MyRequests_btn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Home_btn = new javax.swing.JButton();
        MyRequests_btn = new javax.swing.JButton();
        Shelters_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        profile_btn = new javax.swing.JButton();
        Favourite_btn = new javax.swing.JButton();
        lbl_profile = new javax.swing.JLabel();
        lbl_favourite = new javax.swing.JLabel();
        cb_AdoptionRequestsStatus = new javax.swing.JComboBox<>();
        AdopterAdoptionRequestsScroll = new javax.swing.JScrollPane();
        requestContainerPanel = new javax.swing.JPanel();
        lbl_yourRequests = new javax.swing.JLabel();
        lbl_CountRequests = new javax.swing.JLabel();
        AdopterTotalRequestsCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        Logo.setBackground(new java.awt.Color(255, 153, 51));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        Home_btn.setText("Home");

        MyRequests_btn.setBackground(new java.awt.Color(255, 204, 51));
        MyRequests_btn.setText("My Requests");

        Shelters_btn.setText("Shelters");

        Logout_btn.setText("Logout");

        profile_btn.setBackground(new java.awt.Color(255, 153, 51));
        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileButtonIcon.png"))); // NOI18N
        profile_btn.setBorder(null);

        Favourite_btn.setBackground(new java.awt.Color(255, 153, 51));
        Favourite_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/petFavBtnIcon.png"))); // NOI18N
        Favourite_btn.setBorder(null);

        lbl_profile.setText("Profile");

        lbl_favourite.setText("Favourite");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Logo)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Home_btn)
                        .addGap(18, 18, 18)
                        .addComponent(MyRequests_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Shelters_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Logout_btn)
                        .addGap(93, 93, 93)
                        .addComponent(Favourite_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_favourite)
                        .addGap(209, 209, 209)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_profile))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Favourite_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Home_btn)
                                .addComponent(MyRequests_btn)
                                .addComponent(Shelters_btn)
                                .addComponent(Logout_btn))
                            .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_profile)
                            .addComponent(lbl_favourite))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );

        cb_AdoptionRequestsStatus.setBackground(new java.awt.Color(255, 153, 51));
        cb_AdoptionRequestsStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Accepted", "Pending", "Declined" }));

        requestContainerPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout requestContainerPanelLayout = new javax.swing.GroupLayout(requestContainerPanel);
        requestContainerPanel.setLayout(requestContainerPanelLayout);
        requestContainerPanelLayout.setHorizontalGroup(
            requestContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        requestContainerPanelLayout.setVerticalGroup(
            requestContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        AdopterAdoptionRequestsScroll.setViewportView(requestContainerPanel);

        lbl_yourRequests.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_yourRequests.setText("Your Requests");

        lbl_CountRequests.setText("Total Adoption Requests Count:");

        AdopterTotalRequestsCount.setText("3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_AdoptionRequestsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdopterAdoptionRequestsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_yourRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_CountRequests)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdopterTotalRequestsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_yourRequests)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_AdoptionRequestsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CountRequests)
                    .addComponent(AdopterTotalRequestsCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdopterAdoptionRequestsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdoptionRequestTrackingPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AdopterAdoptionRequestsScroll;
    private javax.swing.JLabel AdopterTotalRequestsCount;
    private javax.swing.JButton Favourite_btn;
    private javax.swing.JButton Home_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JButton MyRequests_btn;
    private javax.swing.JButton Shelters_btn;
    private javax.swing.JComboBox<String> cb_AdoptionRequestsStatus;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_CountRequests;
    private javax.swing.JLabel lbl_favourite;
    private javax.swing.JLabel lbl_profile;
    private javax.swing.JLabel lbl_yourRequests;
    private javax.swing.JButton profile_btn;
    private javax.swing.JPanel requestContainerPanel;
    // End of variables declaration//GEN-END:variables
}
