/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.NavigationController;
import Controller.AdoptionRequestTrackingController;
import java.awt.event.ActionListener;


/**
 *
 * @author User
 */
public class AdoptionRequestTrackingPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdoptionRequestTrackingPage.class.getName());

    /**
     * Creates new form AdoptionHistory
     */
    
    public AdoptionRequestTrackingPage() {
        initComponents();
        setLocationRelativeTo(null);
        new NavigationController(this); 
        
        new AdoptionRequestTrackingController(this);
    }
    
    //   GETTERS
    public javax.swing.JPanel getRequestContainerPanel() {
        return requestContainerPanel;
    }

    public javax.swing.JScrollPane getAdopterAdoptionRequestsScroll() {
        return AdopterAdoptionRequestsScroll;
    }

    public javax.swing.JLabel getAdopterTotalRequestsCount() {
        return AdopterTotalRequestsCount;
    }
    
    
    // LISTENERS
    public void addHomeListener(ActionListener listener) {
        Home_btn.addActionListener(listener);
    }

    public void addMyRequestsListener(ActionListener listener) {
        MyRequests_btn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    public void addShelterListener(ActionListener listener) {
        Shelters_btn.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Home_btn = new javax.swing.JButton();
        MyRequests_btn = new javax.swing.JButton();
        Shelters_btn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        Favourite_btn = new javax.swing.JButton();
        Favourite_text = new javax.swing.JLabel();
        profile_btn = new javax.swing.JButton();
        Profile_text = new javax.swing.JLabel();
        AdopterAdoptionRequestsScroll = new javax.swing.JScrollPane();
        requestContainerPanel = new javax.swing.JPanel();
        cb_AdoptionRequestsStatus = new javax.swing.JComboBox<>();
        lbl_yourRequests = new javax.swing.JLabel();
        lbl_CountRequests = new javax.swing.JLabel();
        AdopterTotalRequestsCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 100));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 112));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        Home_btn.setText("Home");

        MyRequests_btn.setBackground(new java.awt.Color(255, 204, 51));
        MyRequests_btn.setText("My Requests");

        Shelters_btn.setText("Shelters");

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(this::Logout_btnActionPerformed);

        Favourite_btn.setBackground(new java.awt.Color(255, 153, 51));
        Favourite_btn.setForeground(new java.awt.Color(255, 153, 51));
        Favourite_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/petFavBtnIcon.png"))); // NOI18N
        Favourite_btn.setBorder(null);
        Favourite_btn.addActionListener(this::Favourite_btnActionPerformed);

        Favourite_text.setText("Favourite");

        profile_btn.setBackground(new java.awt.Color(255, 153, 51));
        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileButtonIcon.png"))); // NOI18N
        profile_btn.setBorder(null);
        profile_btn.addActionListener(this::profile_btnActionPerformed);

        Profile_text.setText("profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(Home_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MyRequests_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Shelters_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Logout_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(Favourite_btn)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Favourite_text)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_btn)
                    .addComponent(Profile_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Favourite_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_btn)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Home_btn)
                        .addComponent(MyRequests_btn)
                        .addComponent(Shelters_btn)
                        .addComponent(Logout_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Favourite_text)
                    .addComponent(Profile_text))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(17, 17, 17))
        );

        requestContainerPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout requestContainerPanelLayout = new javax.swing.GroupLayout(requestContainerPanel);
        requestContainerPanel.setLayout(requestContainerPanelLayout);
        requestContainerPanelLayout.setHorizontalGroup(
            requestContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        requestContainerPanelLayout.setVerticalGroup(
            requestContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        AdopterAdoptionRequestsScroll.setViewportView(requestContainerPanel);

        cb_AdoptionRequestsStatus.setBackground(new java.awt.Color(255, 153, 51));
        cb_AdoptionRequestsStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Accepted", "Pending", "Declined" }));

        lbl_yourRequests.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_yourRequests.setText("Your Requests");

        lbl_CountRequests.setText("Total Adoption Requests Count:");

        AdopterTotalRequestsCount.setText("3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdopterAdoptionRequestsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_CountRequests)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdopterTotalRequestsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_yourRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_AdoptionRequestsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lbl_yourRequests)
                .addGap(18, 18, 18)
                .addComponent(cb_AdoptionRequestsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CountRequests)
                    .addComponent(AdopterTotalRequestsCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdopterAdoptionRequestsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed

    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Favourite_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Favourite_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Favourite_btnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdoptionRequestTrackingPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AdopterAdoptionRequestsScroll;
    private javax.swing.JLabel AdopterTotalRequestsCount;
    private javax.swing.JButton Favourite_btn;
    private javax.swing.JLabel Favourite_text;
    private javax.swing.JButton Home_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JButton MyRequests_btn;
    private javax.swing.JLabel Profile_text;
    private javax.swing.JButton Shelters_btn;
    private javax.swing.JComboBox<String> cb_AdoptionRequestsStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_CountRequests;
    private javax.swing.JLabel lbl_yourRequests;
    private javax.swing.JButton profile_btn;
    private javax.swing.JPanel requestContainerPanel;
    // End of variables declaration//GEN-END:variables
}
