/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Dell
 */
public class AdoptionRequestManagement_ProviderPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdoptionRequestManagement_ProviderPage.class.getName());

    /**
     * Creates new form AdoptionRequestManagement_ProviderPage
     */
    public AdoptionRequestManagement_ProviderPage() {
        initComponents();
    }
    
    public javax.swing.JPanel getAllPetsRequests_ScrollPanel(){ 
        return AllPetsRequests_ScrollPanel; 
    }
    
    public void addHomeListener(ActionListener listener) {
        Home_btn.addActionListener(listener);
    }

    public void addAdoptionRequestsListener(ActionListener listener) {
        Adoption_requestbtn.addActionListener(listener);
    }
    
    public void addAdoptionHistoryListener(ActionListener listener){
        Adoption_Historybtn.addActionListener(listener);
    } 

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    public void addProfileListener(ActionListener listener) {
        profile_btn.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Searchbar = new javax.swing.JTextField();
        PetRequestsPagePanel = new javax.swing.JPanel();
        Navigation_Panel = new javax.swing.JPanel();
        Home_btn = new javax.swing.JButton();
        Adoption_requestbtn = new javax.swing.JButton();
        Adoption_Historybtn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        profile_btn = new javax.swing.JButton();
        Profile_text = new javax.swing.JLabel();
        Searchbar_AdopterAdoptionRequests = new javax.swing.JTextField();
        Search_Btn = new javax.swing.JButton();
        AllPetsRequests_ScrollPane = new javax.swing.JScrollPane();
        AllPetsRequests_ScrollPanel = new javax.swing.JPanel();
        PetAge_Filter = new javax.swing.JComboBox<>();
        Gender_Filter = new javax.swing.JComboBox<>();
        PetType_Filter = new javax.swing.JComboBox<>();
        Clear_Filter = new javax.swing.JButton();

        Searchbar.setForeground(new java.awt.Color(204, 204, 204));
        Searchbar.setText("parrot, husky, home-trained, kathmandu etc...");
        Searchbar.addActionListener(this::SearchbarActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 680));

        PetRequestsPagePanel.setBackground(new java.awt.Color(255, 255, 255));

        Navigation_Panel.setBackground(new java.awt.Color(255, 153, 51));

        Home_btn.setText("Home");
        Home_btn.addActionListener(this::Home_btnActionPerformed);

        Adoption_requestbtn.setBackground(new java.awt.Color(255, 204, 102));
        Adoption_requestbtn.setText("Adoption Requests");
        Adoption_requestbtn.addActionListener(this::Adoption_requestbtnActionPerformed);

        Adoption_Historybtn.setText("Adoption History");

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(this::Logout_btnActionPerformed);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        profile_btn.setBackground(new java.awt.Color(255, 153, 51));
        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileButtonIcon.png"))); // NOI18N
        profile_btn.setBorder(null);
        profile_btn.addActionListener(this::profile_btnActionPerformed);

        Profile_text.setText("profile");

        javax.swing.GroupLayout Navigation_PanelLayout = new javax.swing.GroupLayout(Navigation_Panel);
        Navigation_Panel.setLayout(Navigation_PanelLayout);
        Navigation_PanelLayout.setHorizontalGroup(
            Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navigation_PanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo)
                .addGap(83, 83, 83)
                .addComponent(Home_btn)
                .addGap(18, 18, 18)
                .addComponent(Adoption_requestbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adoption_Historybtn)
                .addGap(24, 24, 24)
                .addComponent(Logout_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addGroup(Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Profile_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        Navigation_PanelLayout.setVerticalGroup(
            Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navigation_PanelLayout.createSequentialGroup()
                .addGroup(Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Navigation_PanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(Navigation_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home_btn)
                            .addComponent(Adoption_requestbtn)
                            .addComponent(Logout_btn)
                            .addComponent(Adoption_Historybtn)))
                    .addGroup(Navigation_PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Profile_text))
                    .addGroup(Navigation_PanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Searchbar_AdopterAdoptionRequests.setForeground(new java.awt.Color(204, 204, 204));
        Searchbar_AdopterAdoptionRequests.setText("pet name, house-trained, kathmandu etc ");
        Searchbar_AdopterAdoptionRequests.addActionListener(this::Searchbar_AdopterAdoptionRequestsActionPerformed);

        Search_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N

        AllPetsRequests_ScrollPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout AllPetsRequests_ScrollPanelLayout = new javax.swing.GroupLayout(AllPetsRequests_ScrollPanel);
        AllPetsRequests_ScrollPanel.setLayout(AllPetsRequests_ScrollPanelLayout);
        AllPetsRequests_ScrollPanelLayout.setHorizontalGroup(
            AllPetsRequests_ScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        AllPetsRequests_ScrollPanelLayout.setVerticalGroup(
            AllPetsRequests_ScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        AllPetsRequests_ScrollPane.setViewportView(AllPetsRequests_ScrollPanel);

        PetAge_Filter.setBackground(new java.awt.Color(255, 153, 51));
        PetAge_Filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age", "2", "4", "6", "Other..", " " }));

        Gender_Filter.setBackground(new java.awt.Color(255, 153, 51));
        Gender_Filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female" }));

        PetType_Filter.setBackground(new java.awt.Color(255, 153, 51));
        PetType_Filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pet Type", "Dog", "Cat", "Bird", "Marine", "Others", " " }));

        Clear_Filter.setBackground(new java.awt.Color(255, 153, 51));
        Clear_Filter.setText("Clear");

        javax.swing.GroupLayout PetRequestsPagePanelLayout = new javax.swing.GroupLayout(PetRequestsPagePanel);
        PetRequestsPagePanel.setLayout(PetRequestsPagePanelLayout);
        PetRequestsPagePanelLayout.setHorizontalGroup(
            PetRequestsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navigation_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PetRequestsPagePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(AllPetsRequests_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PetRequestsPagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PetRequestsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PetRequestsPagePanelLayout.createSequentialGroup()
                        .addComponent(PetType_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gender_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PetAge_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clear_Filter))
                    .addGroup(PetRequestsPagePanelLayout.createSequentialGroup()
                        .addComponent(Searchbar_AdopterAdoptionRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(256, 256, 256))
        );
        PetRequestsPagePanelLayout.setVerticalGroup(
            PetRequestsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetRequestsPagePanelLayout.createSequentialGroup()
                .addComponent(Navigation_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(PetRequestsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchbar_AdopterAdoptionRequests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PetRequestsPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PetAge_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PetType_Filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear_Filter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(AllPetsRequests_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PetRequestsPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PetRequestsPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 1016, 725);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbarActionPerformed

    private void Searchbar_AdopterAdoptionRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchbar_AdopterAdoptionRequestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Searchbar_AdopterAdoptionRequestsActionPerformed

    private void Adoption_requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adoption_requestbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adoption_requestbtnActionPerformed

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed

    }//GEN-LAST:event_Logout_btnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_btnActionPerformed

    private void Home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdoptionRequestManagement_ProviderPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adoption_Historybtn;
    private javax.swing.JButton Adoption_requestbtn;
    private javax.swing.JScrollPane AllPetsRequests_ScrollPane;
    private javax.swing.JPanel AllPetsRequests_ScrollPanel;
    private javax.swing.JButton Clear_Filter;
    private javax.swing.JComboBox<String> Gender_Filter;
    private javax.swing.JButton Home_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JPanel Navigation_Panel;
    private javax.swing.JComboBox<String> PetAge_Filter;
    private javax.swing.JPanel PetRequestsPagePanel;
    private javax.swing.JComboBox<String> PetType_Filter;
    private javax.swing.JLabel Profile_text;
    private javax.swing.JButton Search_Btn;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JTextField Searchbar_AdopterAdoptionRequests;
    private javax.swing.JButton profile_btn;
    // End of variables declaration//GEN-END:variables
}
