/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.AdoptionRequestData;

/**
 *
 * @author User
 */
public class AdopterRequestCard extends javax.swing.JPanel {

    /**
     * Creates new form AdopterRequestCard
     */
    public AdopterRequestCard(AdoptionRequestData req) {
        initComponents();
        
        setPreferredSize(new java.awt.Dimension(905, 340));
        setMaximumSize(new java.awt.Dimension(905, 340));
        setMinimumSize(new java.awt.Dimension(905, 340));
        
        
        
        LblRequestCardPetName.setText(req.getPetName());
        LblRequestCardPetBreed.setText(req.getPetBreed());
        LblRequestCardPetAge.setText(req.getPetAge());
        LblRequestCardPetGender.setText(req.getPetGender());
        LblRequestStatus.setText(req.getAdoptionStatus());

    setStatusColor(req.getAdoptionStatus());
    loadImage(req.getImagePath());
    
     String status = req.getAdoptionStatus();
     
    if(status.equalsIgnoreCase("Pending")) {

        BtnCancelRequestCard.setVisible(true);
        BtnDeleteRequestCard.setVisible(false);

    }
    else if(status.equalsIgnoreCase("Declined")) {

        BtnCancelRequestCard.setVisible(false);
        BtnDeleteRequestCard.setVisible(true);

    }
    else if(status.equalsIgnoreCase("Accepted")) {

        BtnCancelRequestCard.setVisible(false);
        BtnDeleteRequestCard.setVisible(false);

    }
        
    }
private void setStatusColor(String status) {

    if (status == null) return;

    status = status.toLowerCase();

    if (status.equals("pending")) {
        LblRequestStatus.setOpaque(true);
        LblRequestStatus.setBackground(new java.awt.Color(255, 204, 0)); // yellow
    } 
    else if (status.equals("accepted")) {
        LblRequestStatus.setOpaque(true);
        LblRequestStatus.setBackground(new java.awt.Color(46, 204, 113)); // green
    } 
    else if (status.equals("declined") || status.equals("rejected")) {
        LblRequestStatus.setOpaque(true);
        LblRequestStatus.setBackground(new java.awt.Color(231, 76, 60)); // red
    }
}

private void loadImage(String path) {

    try {

        ImageIcon icon = new ImageIcon(path);

        Image img = icon.getImage().getScaledInstance(
            120,
            120,
            Image.SCALE_SMOOTH
        );

        PetImgRequestCard.setIcon(new ImageIcon(img));

    } catch (Exception e) {

        System.out.println("Image load error: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnVIewMoreRequestCard = new javax.swing.JButton();
        BtnCancelRequestCard = new javax.swing.JButton();
        BtnDeleteRequestCard = new javax.swing.JButton();
        LblRequestStatus = new javax.swing.JLabel();
        PetImgRequestCard = new javax.swing.JLabel();
        BreedRequestCard = new javax.swing.JLabel();
        GenderRequestCard = new javax.swing.JLabel();
        AgeRequestCard = new javax.swing.JLabel();
        LblRequestCardPetBreed = new javax.swing.JLabel();
        LblRequestCardPetGender = new javax.swing.JLabel();
        LblRequestCardPetAge = new javax.swing.JLabel();
        LblRequestCardPetName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 230, 182));

        BtnVIewMoreRequestCard.setText("View More");

        BtnCancelRequestCard.setText("Cancel");

        BtnDeleteRequestCard.setText("Delete");

        LblRequestStatus.setBackground(new java.awt.Color(255, 255, 255));
        LblRequestStatus.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LblRequestStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblRequestStatus.setText("Approved");

        PetImgRequestCard.setText("jLabel4");

        BreedRequestCard.setText("Breed:");

        GenderRequestCard.setText("Gender:");

        AgeRequestCard.setText("Age:");

        LblRequestCardPetBreed.setText("Pet Breed");

        LblRequestCardPetGender.setText("Pet Gender");

        LblRequestCardPetAge.setText("jLabel7");

        LblRequestCardPetName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblRequestCardPetName.setText("Jonny");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblRequestStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PetImgRequestCard, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(LblRequestCardPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AgeRequestCard)
                            .addComponent(GenderRequestCard)
                            .addComponent(BreedRequestCard))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblRequestCardPetBreed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblRequestCardPetGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblRequestCardPetAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnVIewMoreRequestCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCancelRequestCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDeleteRequestCard, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LblRequestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnVIewMoreRequestCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCancelRequestCard))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(LblRequestCardPetName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PetImgRequestCard, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BreedRequestCard)
                                    .addComponent(LblRequestCardPetBreed))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(GenderRequestCard)
                                    .addComponent(LblRequestCardPetGender))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AgeRequestCard)
                                    .addComponent(LblRequestCardPetAge))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDeleteRequestCard)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeRequestCard;
    private javax.swing.JLabel BreedRequestCard;
    private javax.swing.JButton BtnCancelRequestCard;
    private javax.swing.JButton BtnDeleteRequestCard;
    private javax.swing.JButton BtnVIewMoreRequestCard;
    private javax.swing.JLabel GenderRequestCard;
    private javax.swing.JLabel LblRequestCardPetAge;
    private javax.swing.JLabel LblRequestCardPetBreed;
    private javax.swing.JLabel LblRequestCardPetGender;
    private javax.swing.JLabel LblRequestCardPetName;
    private javax.swing.JLabel LblRequestStatus;
    private javax.swing.JLabel PetImgRequestCard;
    // End of variables declaration//GEN-END:variables
}
