/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import model.PetsData;

/**
 *
 * @author Dell
 */
public class PetCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetCardPanel
     */
    
    private PetsData pet;
    public PetCardPanel(PetsData pet) {
        initComponents();
        this.pet = pet; 
        
        PetName.setText(pet.getPetName());
        PetType.setText(pet.getPetType());
        PetAge.setText(pet.getPetAge());
        PetGender.setText(pet.getPetGender());
    }
    
    public PetsData getPet() {
        return pet;
    }

    // Getters
    public javax.swing.JLabel getPetName() { 
        return PetName; 
    }
    public javax.swing.JLabel getPetType() { 
        return PetType; 
    }
    public javax.swing.JLabel getPetAge() { 
        return PetAge; 
    }
    public javax.swing.JLabel getPetGender() { 
        return PetGender; 
    }
    public javax.swing.JLabel getPetImg() { 
        return PetImg; 
    }
    
    
    public void hideActionButtons() {
        PetUpdate.setVisible(false);
        PetDelete.setVisible(false);
    }
    
    
    // listeners for update, delete button

    public void addUpdateListener(ActionListener listener) {
        PetUpdate.addActionListener(listener);
    }

    public void addDeleteListener(ActionListener listener) {
        PetDelete.addActionListener(listener);
    }
    
    public void addViewMoreListener(ActionListener listener) {
        btnViewPetDetail.addActionListener(listener);
    }
    
    public void hideFavButton() {
        fav_homePetCard.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PetImg = new javax.swing.JLabel();
        PetName = new javax.swing.JLabel();
        LblPetType = new javax.swing.JLabel();
        PetType = new javax.swing.JLabel();
        LblPetAge = new javax.swing.JLabel();
        PetAge = new javax.swing.JLabel();
        LblPetGender = new javax.swing.JLabel();
        PetGender = new javax.swing.JLabel();
        btnViewPetDetail = new javax.swing.JButton();
        PetUpdate = new javax.swing.JButton();
        PetDelete = new javax.swing.JButton();
        fav_homePetCard = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 215, 147));

        PetImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pfp.png"))); // NOI18N
        PetImg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PetName.setText("Pet Name");

        LblPetType.setText("Type");

        PetType.setText("Pet Type");

        LblPetAge.setText("Age:");

        PetAge.setText("Pet Age");

        LblPetGender.setText("Gender:");

        PetGender.setText("Pet Gender");

        btnViewPetDetail.setText("View More");
        btnViewPetDetail.addActionListener(this::btnViewPetDetailActionPerformed);

        PetUpdate.setText("Update Pet");
        PetUpdate.addActionListener(this::PetUpdateActionPerformed);

        PetDelete.setText("Delete Pet");

        fav_homePetCard.setBackground(new java.awt.Color(249, 215, 147));
        fav_homePetCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/petFavBtnIcon.png"))); // NOI18N
        fav_homePetCard.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblPetAge)
                            .addComponent(LblPetType)
                            .addComponent(LblPetGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PetType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PetAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PetGender, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(PetImg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(PetName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(fav_homePetCard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PetUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(PetDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPetDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(PetImg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fav_homePetCard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(PetName)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPetType)
                    .addComponent(PetType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPetAge)
                    .addComponent(PetAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPetGender)
                    .addComponent(PetGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnViewPetDetail)
                .addGap(18, 18, 18)
                .addComponent(PetUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PetDelete)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPetDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPetDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPetDetailActionPerformed

    private void PetUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPetAge;
    private javax.swing.JLabel LblPetGender;
    private javax.swing.JLabel LblPetType;
    private javax.swing.JLabel PetAge;
    private javax.swing.JButton PetDelete;
    private javax.swing.JLabel PetGender;
    private javax.swing.JLabel PetImg;
    private javax.swing.JLabel PetName;
    private javax.swing.JLabel PetType;
    private javax.swing.JButton PetUpdate;
    private javax.swing.JButton btnViewPetDetail;
    private javax.swing.JButton fav_homePetCard;
    // End of variables declaration//GEN-END:variables
}
