/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.PetsData;

/**
 *
 * @author Dell
 */
public class PetCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetCardPanel
     */
    public PetCardPanel(PetsData pet) {
        initComponents();
        
        setPreferredSize(new java.awt.Dimension(250, 330));
        setMinimumSize(new java.awt.Dimension(250, 330));
        setMaximumSize(new java.awt.Dimension(250, 330));
        
        PetName.setText(pet.getPetName());
        PetBreed.setText(pet.getPetBreed());
        PetAge.setText(pet.getPetAge());
        PetGender.setText(pet.getPetGender());
        
        
        loadImage(pet.getImagePath());
    }

    private void loadImage(String path) {

    try {
        ImageIcon icon = new ImageIcon(path);

        Image img = icon.getImage().getScaledInstance(
                120,
                120,
                Image.SCALE_SMOOTH
        );

        PetImg.setIcon(new ImageIcon(img));

    } catch (Exception e) {
        System.out.println("Image load error: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PetImg = new javax.swing.JLabel();
        PetName = new javax.swing.JLabel();
        LblPetBreed = new javax.swing.JLabel();
        PetBreed = new javax.swing.JLabel();
        LblPetAge = new javax.swing.JLabel();
        PetAge = new javax.swing.JLabel();
        LblPetGender = new javax.swing.JLabel();
        PetGender = new javax.swing.JLabel();
        btnViewPetDetail = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 215, 147));

        PetImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pfp.png"))); // NOI18N
        PetImg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PetName.setText("Pet Name");

        LblPetBreed.setText("Breed:");

        PetBreed.setText("Pet Breed");

        LblPetAge.setText("Age:");

        PetAge.setText("Pet Age");

        LblPetGender.setText("Gender:");

        PetGender.setText("Pet Gender");

        btnViewPetDetail.setText("View More");
        btnViewPetDetail.addActionListener(this::btnViewPetDetailActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(PetImg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(PetName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblPetAge)
                            .addComponent(LblPetBreed)
                            .addComponent(LblPetGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PetBreed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PetAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PetGender, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnViewPetDetail)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PetImg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PetName)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPetBreed)
                    .addComponent(PetBreed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPetAge)
                    .addComponent(PetAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPetGender)
                    .addComponent(PetGender))
                .addGap(27, 27, 27)
                .addComponent(btnViewPetDetail)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPetDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPetDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPetDetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPetAge;
    private javax.swing.JLabel LblPetBreed;
    private javax.swing.JLabel LblPetGender;
    private javax.swing.JLabel PetAge;
    private javax.swing.JLabel PetBreed;
    private javax.swing.JLabel PetGender;
    private javax.swing.JLabel PetImg;
    private javax.swing.JLabel PetName;
    private javax.swing.JButton btnViewPetDetail;
    // End of variables declaration//GEN-END:variables
}
