/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.PetController;
import java.awt.event.ActionListener;




/**
 *
 * @author User
 */
public final class ProviderHomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProviderHomePage.class.getName());

    /**
     * Creates new form PetDisplay
     */
    
    

    public ProviderHomePage() {
    initComponents();
    setLocationRelativeTo(null);
    new PetController(this);  
}

    
    
// GETTERS
public javax.swing.JPanel getProviderPetContainerPanel() {
    return providerPetContainerPanel;
}

public javax.swing.JLabel getTotalPetCountLabel() {
    return TotalPetCount;
}

public javax.swing.JScrollPane getProviderPetsScrollPane() {
    return ProviderPetsScrollPane;
}


// LISTENERS
    public void addPetButtonListener(ActionListener listener) {
        Add_pet_provider.addActionListener(listener);
    }
    
    public void addHomeListener(ActionListener listener) {
        Home_btn.addActionListener(listener);
    }

    public void addAdoptionRequestsListener(ActionListener listener) {
        Adoption_requestbtn.addActionListener(listener);
    }
    
    public void addAdoptionHistoryListener(ActionListener listener){
        Adoption_Historybtn.addActionListener(listener);
    } 

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    public void addProfileListener(ActionListener listener) {
        profile_btn.addActionListener(listener);
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        Main_panal = new javax.swing.JPanel();
        PetFilterClear = new javax.swing.JButton();
        Gender_combobox = new javax.swing.JComboBox<>();
        PetType_combobox = new javax.swing.JComboBox<>();
        Searchbar = new javax.swing.JTextField();
        SearchLogo = new javax.swing.JButton();
        Age_combobox = new javax.swing.JComboBox<>();
        totalpet = new javax.swing.JLabel();
        TotalPetCount = new javax.swing.JLabel();
        ProviderPetsScrollPane = new javax.swing.JScrollPane();
        providerPetContainerPanel = new javax.swing.JPanel();
        Top_panal = new javax.swing.JPanel();
        Home_btn = new javax.swing.JButton();
        Adoption_requestbtn = new javax.swing.JButton();
        Adoption_Historybtn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        profile_btn = new javax.swing.JButton();
        Profile_text = new javax.swing.JLabel();
        Add_pet_provider = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 680));

        Main_panal.setBackground(new java.awt.Color(255, 255, 255));
        Main_panal.setLayout(null);

        PetFilterClear.setBackground(new java.awt.Color(255, 153, 51));
        PetFilterClear.setText("Clear");
        PetFilterClear.addActionListener(this::PetFilterClearActionPerformed);
        Main_panal.add(PetFilterClear);
        PetFilterClear.setBounds(650, 180, 70, 23);

        Gender_combobox.setBackground(new java.awt.Color(255, 153, 51));
        Gender_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female" }));
        Main_panal.add(Gender_combobox);
        Gender_combobox.setBounds(370, 180, 115, 22);

        PetType_combobox.setBackground(new java.awt.Color(255, 153, 51));
        PetType_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pet Type", "Dog", "Cat", "Bird", "Marine", "Others", " " }));
        Main_panal.add(PetType_combobox);
        PetType_combobox.setBounds(250, 180, 115, 22);

        Searchbar.setForeground(new java.awt.Color(204, 204, 204));
        Searchbar.setText("pet name, house-trained, kathmandu etc ");
        Searchbar.addActionListener(this::SearchbarActionPerformed);
        Main_panal.add(Searchbar);
        Searchbar.setBounds(250, 140, 420, 20);

        SearchLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        Main_panal.add(SearchLogo);
        SearchLogo.setBounds(680, 140, 40, 22);

        Age_combobox.setBackground(new java.awt.Color(255, 153, 51));
        Age_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age", "2", "4", "6", "Other..", " " }));
        Main_panal.add(Age_combobox);
        Age_combobox.setBounds(490, 180, 130, 22);

        totalpet.setText("Total Pet:");
        Main_panal.add(totalpet);
        totalpet.setBounds(30, 230, 70, 16);

        TotalPetCount.setText("Pet Count");
        Main_panal.add(TotalPetCount);
        TotalPetCount.setBounds(90, 230, 63, 16);

        providerPetContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        providerPetContainerPanel.setLayout(new java.awt.GridLayout(0, 3, 20, 20));
        ProviderPetsScrollPane.setViewportView(providerPetContainerPanel);

        Main_panal.add(ProviderPetsScrollPane);
        ProviderPetsScrollPane.setBounds(30, 260, 940, 400);

        Top_panal.setBackground(new java.awt.Color(255, 153, 51));
        Top_panal.setPreferredSize(new java.awt.Dimension(1000, 100));

        Home_btn.setBackground(new java.awt.Color(255, 204, 102));
        Home_btn.setText("Home");

        Adoption_requestbtn.setText("Adoption Requests");
        Adoption_requestbtn.addActionListener(this::Adoption_requestbtnActionPerformed);

        Adoption_Historybtn.setText("Adoption History");

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(this::Logout_btnActionPerformed);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        profile_btn.setBackground(new java.awt.Color(255, 153, 51));
        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileButtonIcon.png"))); // NOI18N
        profile_btn.setBorder(null);
        profile_btn.addActionListener(this::profile_btnActionPerformed);

        Profile_text.setText("profile");

        javax.swing.GroupLayout Top_panalLayout = new javax.swing.GroupLayout(Top_panal);
        Top_panal.setLayout(Top_panalLayout);
        Top_panalLayout.setHorizontalGroup(
            Top_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Top_panalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo)
                .addGap(83, 83, 83)
                .addComponent(Home_btn)
                .addGap(18, 18, 18)
                .addComponent(Adoption_requestbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adoption_Historybtn)
                .addGap(24, 24, 24)
                .addComponent(Logout_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addGroup(Top_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Profile_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        Top_panalLayout.setVerticalGroup(
            Top_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Top_panalLayout.createSequentialGroup()
                .addGroup(Top_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Top_panalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(Top_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home_btn)
                            .addComponent(Adoption_requestbtn)
                            .addComponent(Logout_btn)
                            .addComponent(Adoption_Historybtn)))
                    .addGroup(Top_panalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Profile_text))
                    .addGroup(Top_panalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Main_panal.add(Top_panal);
        Top_panal.setBounds(0, 0, 1000, 110);

        Add_pet_provider.setBackground(new java.awt.Color(255, 153, 51));
        Add_pet_provider.setText("Add pet");
        Main_panal.add(Add_pet_provider);
        Add_pet_provider.setBounds(880, 230, 90, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panal, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_panal, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed

    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Adoption_requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adoption_requestbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adoption_requestbtnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_btnActionPerformed

    private void SearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchbarActionPerformed

    private void PetFilterClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetFilterClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetFilterClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProviderHomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_pet_provider;
    private javax.swing.JButton Adoption_Historybtn;
    private javax.swing.JButton Adoption_requestbtn;
    private javax.swing.JComboBox<String> Age_combobox;
    private javax.swing.JComboBox<String> Gender_combobox;
    private javax.swing.JButton Home_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JPanel Main_panal;
    private javax.swing.JButton PetFilterClear;
    private javax.swing.JComboBox<String> PetType_combobox;
    private javax.swing.JLabel Profile_text;
    private javax.swing.JScrollPane ProviderPetsScrollPane;
    private javax.swing.JButton SearchLogo;
    private javax.swing.JTextField Searchbar;
    private javax.swing.JPanel Top_panal;
    private javax.swing.JLabel TotalPetCount;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton profile_btn;
    private javax.swing.JPanel providerPetContainerPanel;
    private javax.swing.JLabel totalpet;
    // End of variables declaration//GEN-END:variables
 
}

