/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ProviderAdoptionHistoryController;
import java.awt.event.ActionListener;


/**
 *
 * @author shank
 */
public class ProviderAdoptionHistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProviderAdoptionHistory.class.getName());

    /**
     * Creates new form ProviderAdoptionHistory
     */
    public ProviderAdoptionHistory() {
        initComponents();
        new ProviderAdoptionHistoryController(this);
    }
    
    public javax.swing.JScrollPane getHistoryScrollPane() {
        return jScrollPane1;
    }
    
    public void addAdoptionHistoryListener(ActionListener listener){
        Adoption_Historybtn.addActionListener(listener);
    }   
    
    public void addHomeListener(ActionListener listener) {
        Home_btn.addActionListener(listener);
    }

    public void addAdoptionRequestsListener(ActionListener listener) {
        Adoption_requestbtn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    
    public javax.swing.JPanel getSpnlAdoptionHistory() {
        return spnlAdoptionHistory;
    }

    public javax.swing.JLabel getlblPetCount() {
        return lblPetCount;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel3 = new javax.swing.JPanel();
        pnlTopBar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        Home_btn = new javax.swing.JButton();
        Adoption_requestbtn = new javax.swing.JButton();
        Adoption_Historybtn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        lblProfile = new javax.swing.JLabel();
        profile_btn = new javax.swing.JButton();
        cbPetType = new javax.swing.JComboBox<>();
        cbGender = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        lblTotalAdoptedPets = new javax.swing.JLabel();
        lblPetCount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        spnlAdoptionHistory = new javax.swing.JPanel();
        cbAge = new javax.swing.JComboBox<>();
        Searchbar1 = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        pnlTopBar.setBackground(new java.awt.Color(255, 153, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N
        lblLogo.setText("jLabel1");

        Home_btn.setText("Home");

        Adoption_requestbtn.setText("Adoption Requests");
        Adoption_requestbtn.addActionListener(this::Adoption_requestbtnActionPerformed);

        Adoption_Historybtn.setBackground(new java.awt.Color(255, 204, 102));
        Adoption_Historybtn.setText("Adoption History");
        Adoption_Historybtn.addActionListener(this::Adoption_HistorybtnActionPerformed);

        Logout_btn.setText("Logout");

        lblProfile.setText("Profile");

        profile_btn.setBackground(new java.awt.Color(255, 153, 0));
        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileButtonIcon.png"))); // NOI18N
        profile_btn.addActionListener(this::profile_btnActionPerformed);

        javax.swing.GroupLayout pnlTopBarLayout = new javax.swing.GroupLayout(pnlTopBar);
        pnlTopBar.setLayout(pnlTopBarLayout);
        pnlTopBarLayout.setHorizontalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(Home_btn)
                .addGap(37, 37, 37)
                .addComponent(Adoption_requestbtn)
                .addGap(43, 43, 43)
                .addComponent(Adoption_Historybtn)
                .addGap(34, 34, 34)
                .addComponent(Logout_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_btn)
                    .addComponent(lblProfile))
                .addGap(69, 69, 69))
        );
        pnlTopBarLayout.setVerticalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopBarLayout.createSequentialGroup()
                        .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLogo)
                            .addComponent(Home_btn)
                            .addComponent(Adoption_requestbtn)
                            .addComponent(Adoption_Historybtn)
                            .addComponent(Logout_btn))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopBarLayout.createSequentialGroup()
                        .addComponent(profile_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfile)
                        .addGap(41, 41, 41))))
        );

        cbPetType.setBackground(new java.awt.Color(255, 153, 51));
        cbPetType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pet Type", "Dog", "Cat", "Hamster" }));

        cbGender.setBackground(new java.awt.Color(255, 153, 51));
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Other", " " }));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        lblTotalAdoptedPets.setText("Total Adopted Pets: ");

        lblPetCount.setText("Pet Count");

        spnlAdoptionHistory.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout spnlAdoptionHistoryLayout = new javax.swing.GroupLayout(spnlAdoptionHistory);
        spnlAdoptionHistory.setLayout(spnlAdoptionHistoryLayout);
        spnlAdoptionHistoryLayout.setHorizontalGroup(
            spnlAdoptionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1669, Short.MAX_VALUE)
        );
        spnlAdoptionHistoryLayout.setVerticalGroup(
            spnlAdoptionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(spnlAdoptionHistory);

        cbAge.setBackground(new java.awt.Color(255, 153, 51));
        cbAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age", "New Born (<1 year)", "Young (1-3  year)", "Adult  (3-8 year)", "Senior (8> year)" }));

        Searchbar1.setForeground(new java.awt.Color(204, 204, 204));
        Searchbar1.setText("Jonny, parrot, husky, home-trained, kathmandu etc...");
        Searchbar1.addActionListener(this::Searchbar1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(cbPetType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbAge, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTotalAdoptedPets)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPetCount)
                                .addGap(401, 401, 401)))
                        .addGap(373, 373, 373))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Searchbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnlTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Searchbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPetType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalAdoptedPets)
                    .addComponent(lblPetCount))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Adoption_HistorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adoption_HistorybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adoption_HistorybtnActionPerformed

    private void Adoption_requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adoption_requestbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adoption_requestbtnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_btnActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void Searchbar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchbar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Searchbar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProviderAdoptionHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adoption_Historybtn;
    private javax.swing.JButton Adoption_requestbtn;
    private javax.swing.JButton Home_btn;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JTextField Searchbar1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbAge;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbPetType;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPetCount;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblTotalAdoptedPets;
    private javax.swing.JPanel pnlTopBar;
    private javax.swing.JButton profile_btn;
    private javax.swing.JPanel spnlAdoptionHistory;
    // End of variables declaration//GEN-END:variables
}
