/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author shank
 */
public class ProviderProfileUpdate extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProviderProfileUpdate.class.getName());

    /**
     * Creates new form ProviderProfileUpdate
     */
    public ProviderProfileUpdate() {
        initComponents();
    }
    public void addSaveListener(java.awt.event.ActionListener listener){
        btnSave.addActionListener(listener); 
    }
    public void addChangeImageListener(java.awt.event.ActionListener listener){
        btnChangeImage.addActionListener(listener);
    }

    // ===== GETTERS =====
    public javax.swing.JLabel getProfileImgLabel(){
        return ProfileImg;
    }
    public String getShelterName(){
        return txtShelterName.getText();
    }
    public String getUsername(){
        return txtUsername.getText();
    }
    public String getLicenseID(){
        return txtLicenseID.getText();
    }
    public String getPhoneNumber(){
        return txtPhoneNumber.getText();
    }
    public String getEmail(){
        return txtEmail.getText();
    }
    public String getAddress(){
        return txtAddress.getText();
    }
    public String getMissionStatement(){
        return txtMissionStatement.getText();
    }
    public String getAdoptionPolicy(){
        return txtAdoptionPolicy.getText();
    }
    public String getStartTime(){
        return StartTime.getSelectedItem().toString();
    }
    public String getEndTime(){
        return EndTime.getSelectedItem().toString();
    }
    public String getStartDay(){
        return StartDay.getSelectedItem().toString();
    }
    public String getEndDay(){
        return EndDay.getSelectedItem().toString();
    }


    // ===== SETTERS =====
    public void setShelterName(String shelterName){
        txtShelterName.setText(shelterName);
    }
    public void setUsername(String username){
        txtUsername.setText(username);
    }
    public void setLicenseID(String licenseID){
        txtLicenseID.setText(licenseID);
    }
    public void setPhoneNumber(String phoneNumber){
        txtPhoneNumber.setText(phoneNumber);
    }
    public void setEmail(String email){
        txtEmail.setText(email);
    }
    public void setAddress(String address){
        txtAddress.setText(address);
    }
    public void setMissionStatement(String missionStatement){
        txtMissionStatement.setText(missionStatement);
    }
    public void setAdoptionPolicy(String adoptionPolicy){
        txtAdoptionPolicy.setText(adoptionPolicy);
    }
    public void setStartTime(String startTime){
        StartTime.setSelectedItem(startTime);
    }
    public void setEndTime(String endTime){
        EndTime.setSelectedItem(endTime);
    }
    public void setStartDay(String startDay){
        StartDay.setSelectedItem(startDay);
    }
    public void setEndDay(String endDay){
        EndDay.setSelectedItem(endDay);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProfileImg = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblShelterName = new javax.swing.JLabel();
        lblLicenseID = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtShelterName = new javax.swing.JTextField();
        txtLicenseID = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblWorkingTime = new javax.swing.JLabel();
        lblWorkingDays = new javax.swing.JLabel();
        StartTime = new javax.swing.JComboBox<>();
        EndTime = new javax.swing.JComboBox<>();
        StartDay = new javax.swing.JComboBox<>();
        EndDay = new javax.swing.JComboBox<>();
        lblAdoptionPolicy = new javax.swing.JLabel();
        lblMissionStatement = new javax.swing.JLabel();
        spMissionStatement = new javax.swing.JScrollPane();
        txtMissionStatement = new javax.swing.JTextArea();
        spAdoptionPolicy = new javax.swing.JScrollPane();
        txtAdoptionPolicy = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnChangeImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ProfileImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pfp.png"))); // NOI18N
        ProfileImg.setText("jLabel1");

        lblUsername.setText("Username:");

        lblShelterName.setText("Shelter Name:");

        lblLicenseID.setText("License ID:");

        lblPhoneNumber.setText("Phone Number:");

        lblEmail.setText("Email:");

        lblAddress.setText("Address:");

        txtPhoneNumber.addActionListener(this::txtPhoneNumberActionPerformed);

        lblWorkingTime.setText("Working Hours:");

        lblWorkingDays.setText("Working Days:");

        StartTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));

        EndTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));

        StartDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sun", "Mon", "Tue", "Wed", "Thur", "Fri", "Sat" }));

        EndDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sun", "Mon", "Tue", "Wed", "Thur", "Fri", "Sat" }));

        lblAdoptionPolicy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdoptionPolicy.setText("Adoption Policy:");

        lblMissionStatement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMissionStatement.setText("Mission Statement:");

        txtMissionStatement.setColumns(20);
        txtMissionStatement.setRows(5);
        spMissionStatement.setViewportView(txtMissionStatement);

        txtAdoptionPolicy.setColumns(20);
        txtAdoptionPolicy.setRows(5);
        spAdoptionPolicy.setViewportView(txtAdoptionPolicy);

        btnSave.setBackground(new java.awt.Color(255, 204, 51));
        btnSave.setText("Save");

        btnChangeImage.setText("Change Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPhoneNumber)
                            .addComponent(lblUsername)
                            .addComponent(lblShelterName)
                            .addComponent(lblLicenseID)
                            .addComponent(lblEmail)
                            .addComponent(lblAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblWorkingTime)
                                .addGap(18, 18, 18)
                                .addComponent(StartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtShelterName, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                .addComponent(txtUsername)
                                .addComponent(txtLicenseID)
                                .addComponent(txtPhoneNumber)
                                .addComponent(txtAddress)
                                .addComponent(txtEmail))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblWorkingDays)
                                .addGap(18, 18, 18)
                                .addComponent(StartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ProfileImg, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(228, 228, 228))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnChangeImage)
                                .addGap(211, 211, 211)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMissionStatement)
                    .addComponent(lblAdoptionPolicy)
                    .addComponent(spAdoptionPolicy, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(spMissionStatement))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(228, 228, 228))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(ProfileImg, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMissionStatement)
                    .addComponent(btnChangeImage))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMissionStatement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShelterName)
                            .addComponent(txtShelterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblAdoptionPolicy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spAdoptionPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLicenseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicenseID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWorkingTime)
                            .addComponent(StartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWorkingDays)
                            .addComponent(StartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProviderProfileUpdate().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EndDay;
    private javax.swing.JComboBox<String> EndTime;
    private javax.swing.JLabel ProfileImg;
    private javax.swing.JComboBox<String> StartDay;
    private javax.swing.JComboBox<String> StartTime;
    private javax.swing.JButton btnChangeImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAdoptionPolicy;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLicenseID;
    private javax.swing.JLabel lblMissionStatement;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblShelterName;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWorkingDays;
    private javax.swing.JLabel lblWorkingTime;
    private javax.swing.JScrollPane spAdoptionPolicy;
    private javax.swing.JScrollPane spMissionStatement;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextArea txtAdoptionPolicy;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLicenseID;
    private javax.swing.JTextArea txtMissionStatement;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtShelterName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
