/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ProviderProfileController;
import java.awt.event.ActionListener;

/**
 *
 * @author shank
 */
public class ProviderProfile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProviderProfile.class.getName());

    /**
     * Creates new form ProviderProfile
     */
    public ProviderProfile() {
        initComponents();
        
         lblMissionStatement_fill.setPreferredSize(new java.awt.Dimension(390, 90));
        lblAdoptionPolicy_fill.setPreferredSize(new java.awt.Dimension(390, 90));

   
        lblMissionStatement_fill.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblAdoptionPolicy_fill.setVerticalAlignment(javax.swing.SwingConstants.TOP);

  
        java.net.URL profileIconUrl = getClass().getResource("/Images/profileButtonIcon.png");
        if (profileIconUrl != null) {
            javax.swing.ImageIcon rawIcon = new javax.swing.ImageIcon(profileIconUrl);
            java.awt.Image scaled = rawIcon.getImage().getScaledInstance(25, 25, java.awt.Image.SCALE_SMOOTH);
            profile_btn.setIcon(new javax.swing.ImageIcon(scaled));
        } else {
            logger.warning("profileButtonIcon.png not found on classpath at /Images/profileButtonIcon.png");
        }
    }
    
    
    private String escapeHtml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\n", "<br>");
    }

    public void setlblMissionStatement_fill(String mission) {
        lblMissionStatement_fill.setText("<html><body style='width:390px'>" + escapeHtml(mission) + "</body></html>");
    }

    public void setlblAdoptionPolicy_fill(String policy) {
        lblAdoptionPolicy_fill.setText("<html><body style='width:390px'>" + escapeHtml(policy) + "</body></html>");
    }

    public void addEditListener(ActionListener listener) {
        btnEdit.addActionListener(listener);
    }

    public void addChangePasswordListener(ActionListener listener) {
        btnChangePassword.addActionListener(listener);
    }
    
    public javax.swing.JLabel getlblShelterName_fill(){
        return lblShelterName_fill;
    }
    public void setlblShelterName_fill(String name) {
        lblShelterName_fill.setText(name);
    }


    public void setlblPhoneNumber_fill(String phone) {
        lblPhoneNumber_fill.setText(phone);
    }

  
    public void setlblEmail_fill(String email) {
        lblEmail_fill.setText(email);
    }


    public void setlblLocation_fill(String location) {
        lblLocation_fill.setText(location);
    }
    
    public void setlblStartHour_fill(String startHour) {
        StartHour_ProfileLbl.setText(startHour);
    }
    
    public void setlblEndHour_fill(String endHour) {
        EndHour_ProfileLbl.setText(endHour);
    }
    
    public void setlblStartDay_fill(String startDay) {
        StartDay_ProfileLbl.setText(startDay);
    }
    
    public void setlblEndDay_fill(String endDay) {
        EndDay_Profilelbl.setText(endDay);
    }
    
    

    public javax.swing.JLabel getlblPhoneNumber_fill(){
        return lblPhoneNumber_fill;
    }

    public javax.swing.JLabel getlblEmail_fill(){
        return lblEmail_fill;
    }

    public javax.swing.JLabel getlblLocation_fill(){
        return lblLocation_fill;
    }

    public javax.swing.JLabel getlblMissionStatement_fill(){
        return lblMissionStatement_fill;
    }

    public javax.swing.JLabel getlblAdoptionPolicy_fill(){
        return lblAdoptionPolicy_fill;
    }
    public javax.swing.JLabel getlblProfile(){
        return lblProfile;
    }
    public void setlblProfile(String name) {
        lblProfile.setText(name);
    }
    
    
    public void addHomeListener(ActionListener listener) {
        Home_btn.addActionListener(listener);
    }

    public void addAdoptionRequestsListener(ActionListener listener) {
        Adoption_requestbtn.addActionListener(listener);
    }
    
    public void addAdoptionHistoryListener(ActionListener listener){
        Adoption_Historybtn.addActionListener(listener);
    } 

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    public void addProfileListener(ActionListener listener) {
        profile_btn.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTopBar = new javax.swing.JPanel();
        Adoption_Historybtn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        profile_btn = new javax.swing.JButton();
        Profile_text = new javax.swing.JLabel();
        Home_btn = new javax.swing.JButton();
        Adoption_requestbtn = new javax.swing.JButton();
        lblProfile = new javax.swing.JLabel();
        lblShelterName_fill = new javax.swing.JLabel();
        lblContacts = new javax.swing.JLabel();
        lblPhoneNumber_fill = new javax.swing.JLabel();
        lblEmail_fill = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblLocation_fill = new javax.swing.JLabel();
        lblMissionStatement = new javax.swing.JLabel();
        lblAdoptionHistory = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblMissionStatement_fill = new javax.swing.JLabel();
        lblAdoptionPolicy_fill = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StartHour_ProfileLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EndHour_ProfileLbl = new javax.swing.JLabel();
        StartDay_ProfileLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EndDay_Profilelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 679));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlTopBar.setBackground(new java.awt.Color(255, 153, 0));

        Adoption_Historybtn.setText("Adoption History");

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(this::Logout_btnActionPerformed);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        profile_btn.setBackground(new java.awt.Color(255, 153, 51));
        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileButtonIcon.png"))); // NOI18N
        profile_btn.setBorder(null);
        profile_btn.addActionListener(this::profile_btnActionPerformed);

        Profile_text.setText("profile");

        Home_btn.setText("Home");

        Adoption_requestbtn.setText("Adoption Requests");
        Adoption_requestbtn.addActionListener(this::Adoption_requestbtnActionPerformed);

        javax.swing.GroupLayout pnlTopBarLayout = new javax.swing.GroupLayout(pnlTopBar);
        pnlTopBar.setLayout(pnlTopBarLayout);
        pnlTopBarLayout.setHorizontalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo)
                .addGap(83, 83, 83)
                .addComponent(Home_btn)
                .addGap(18, 18, 18)
                .addComponent(Adoption_requestbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adoption_Historybtn)
                .addGap(24, 24, 24)
                .addComponent(Logout_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Profile_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        pnlTopBarLayout.setVerticalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopBarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home_btn)
                            .addComponent(Adoption_requestbtn)
                            .addComponent(Logout_btn)
                            .addComponent(Adoption_Historybtn)))
                    .addGroup(pnlTopBarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Profile_text))
                    .addGroup(pnlTopBarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblProfile.setText("ProfilePfp");

        lblShelterName_fill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblShelterName_fill.setText("ShelterName_fill");

        lblContacts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContacts.setText("Contacts:");

        lblPhoneNumber_fill.setText("PhoneNumber_fill");

        lblEmail_fill.setText("Email_fill");

        lblLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLocation.setText("Location:");

        lblLocation_fill.setText("Location_fill");

        lblMissionStatement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMissionStatement.setText("Mission Statement:");

        lblAdoptionHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdoptionHistory.setText("Adoption History:");

        btnChangePassword.setBackground(new java.awt.Color(255, 204, 0));
        btnChangePassword.setText("Change Password");

        btnEdit.setBackground(new java.awt.Color(255, 204, 51));
        btnEdit.setText("Edit");

        lblMissionStatement_fill.setText("MissionStatement_fill");

        lblAdoptionPolicy_fill.setText("AdoptionPolicy_fill");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Working Hours:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Working Days:");

        StartHour_ProfileLbl.setText("Start Hour");

        jLabel4.setText("-");

        EndHour_ProfileLbl.setText("End Hour");

        StartDay_ProfileLbl.setText("Start Day");

        jLabel7.setText("-");

        EndDay_Profilelbl.setText("End Day");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail_fill)
                    .addComponent(lblLocation)
                    .addComponent(lblLocation_fill)
                    .addComponent(lblPhoneNumber_fill)
                    .addComponent(lblContacts)
                    .addComponent(lblShelterName_fill, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StartHour_ProfileLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(EndHour_ProfileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StartDay_ProfileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(EndDay_Profilelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdoptionHistory)
                    .addComponent(lblMissionStatement)
                    .addComponent(lblMissionStatement_fill, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdoptionPolicy_fill, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnChangePassword))
                    .addComponent(btnEdit))
                .addGap(321, 321, 321))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblMissionStatement)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMissionStatement_fill, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblShelterName_fill)
                                .addGap(33, 33, 33)
                                .addComponent(lblContacts)
                                .addGap(18, 18, 18)
                                .addComponent(lblPhoneNumber_fill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmail_fill)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(lblAdoptionHistory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAdoptionPolicy_fill, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLocation_fill)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StartHour_ProfileLbl)
                                    .addComponent(jLabel4)
                                    .addComponent(EndHour_ProfileLbl))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StartDay_ProfileLbl)
                                    .addComponent(jLabel7)
                                    .addComponent(EndDay_Profilelbl))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword)
                    .addComponent(btnEdit))
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-4, -5, 1010, 720);

        setBounds(0, 0, 1016, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed

    }//GEN-LAST:event_Logout_btnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_btnActionPerformed

    private void Adoption_requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adoption_requestbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adoption_requestbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProviderProfile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adoption_Historybtn;
    private javax.swing.JButton Adoption_requestbtn;
    private javax.swing.JLabel EndDay_Profilelbl;
    private javax.swing.JLabel EndHour_ProfileLbl;
    private javax.swing.JButton Home_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JLabel Profile_text;
    private javax.swing.JLabel StartDay_ProfileLbl;
    private javax.swing.JLabel StartHour_ProfileLbl;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdoptionHistory;
    private javax.swing.JLabel lblAdoptionPolicy_fill;
    private javax.swing.JLabel lblContacts;
    private javax.swing.JLabel lblEmail_fill;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLocation_fill;
    private javax.swing.JLabel lblMissionStatement;
    private javax.swing.JLabel lblMissionStatement_fill;
    private javax.swing.JLabel lblPhoneNumber_fill;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblShelterName_fill;
    private javax.swing.JPanel pnlTopBar;
    private javax.swing.JButton profile_btn;
    // End of variables declaration//GEN-END:variables
}
