/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ProviderAdoptionHistoryController;
import java.awt.event.ActionListener;


/**
 *
 * @author shank
 */
public class ProviderAdoptionHistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProviderAdoptionHistory.class.getName());

    /**
     * Creates new form ProviderAdoptionHistory
     */
    public ProviderAdoptionHistory() {
        initComponents();
        new ProviderAdoptionHistoryController(this);
    }
    
    public javax.swing.JScrollPane getHistoryScrollPane() {
        return jScrollPane1;
    }
    
    public void addAdoptionHistoryListener(ActionListener listener){
        Adoption_Historybtn.addActionListener(listener);
    }   
    
    public void addHomeListener(ActionListener listener) {
        Home_btn.addActionListener(listener);
    }

    public void addAdoptionRequestsListener(ActionListener listener) {
        Adoption_requestbtn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        Logout_btn.addActionListener(listener);
    }
    
    
    public javax.swing.JPanel getSpnlAdoptionHistory() {
        return spnlAdoptionHistory;
    }

    public javax.swing.JLabel getlblPetCount() {
        return lblPetCount;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel3 = new javax.swing.JPanel();
        pnlTopBar = new javax.swing.JPanel();
        Home_btn = new javax.swing.JButton();
        Adoption_requestbtn = new javax.swing.JButton();
        Adoption_Historybtn = new javax.swing.JButton();
        Logout_btn = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        profile_btn = new javax.swing.JButton();
        Profile_text = new javax.swing.JLabel();
        cbPetType = new javax.swing.JComboBox<>();
        cbGender = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        lblTotalAdoptedPets = new javax.swing.JLabel();
        lblPetCount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        spnlAdoptionHistory = new javax.swing.JPanel();
        cbAge = new javax.swing.JComboBox<>();
        Searchbar1 = new javax.swing.JTextField();
        PetFilterClear = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        pnlTopBar.setBackground(new java.awt.Color(255, 153, 0));
        pnlTopBar.setPreferredSize(new java.awt.Dimension(1000, 110));

        Home_btn.setText("Home");

        Adoption_requestbtn.setText("Adoption Requests");
        Adoption_requestbtn.addActionListener(this::Adoption_requestbtnActionPerformed);

        Adoption_Historybtn.setBackground(new java.awt.Color(255, 204, 102));
        Adoption_Historybtn.setText("Adoption History");

        Logout_btn.setText("Logout");
        Logout_btn.addActionListener(this::Logout_btnActionPerformed);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pas_circular_logo.png"))); // NOI18N

        profile_btn.setBackground(new java.awt.Color(255, 153, 51));
        profile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileButtonIcon.png"))); // NOI18N
        profile_btn.setBorder(null);
        profile_btn.addActionListener(this::profile_btnActionPerformed);

        Profile_text.setText("profile");

        javax.swing.GroupLayout pnlTopBarLayout = new javax.swing.GroupLayout(pnlTopBar);
        pnlTopBar.setLayout(pnlTopBarLayout);
        pnlTopBarLayout.setHorizontalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Logo)
                .addGap(83, 83, 83)
                .addComponent(Home_btn)
                .addGap(18, 18, 18)
                .addComponent(Adoption_requestbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adoption_Historybtn)
                .addGap(24, 24, 24)
                .addComponent(Logout_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Profile_text, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        pnlTopBarLayout.setVerticalGroup(
            pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBarLayout.createSequentialGroup()
                .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopBarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnlTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home_btn)
                            .addComponent(Adoption_requestbtn)
                            .addComponent(Logout_btn)
                            .addComponent(Adoption_Historybtn)))
                    .addGroup(pnlTopBarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(profile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Profile_text))
                    .addGroup(pnlTopBarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cbPetType.setBackground(new java.awt.Color(255, 153, 51));
        cbPetType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pet Type", "Dog", "Cat", "Birds", "Marine", "Others" }));

        cbGender.setBackground(new java.awt.Color(255, 153, 51));
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Other", " " }));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        lblTotalAdoptedPets.setText("Total Adopted Pets: ");

        lblPetCount.setText("Pet Count");

        spnlAdoptionHistory.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout spnlAdoptionHistoryLayout = new javax.swing.GroupLayout(spnlAdoptionHistory);
        spnlAdoptionHistory.setLayout(spnlAdoptionHistoryLayout);
        spnlAdoptionHistoryLayout.setHorizontalGroup(
            spnlAdoptionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1669, Short.MAX_VALUE)
        );
        spnlAdoptionHistoryLayout.setVerticalGroup(
            spnlAdoptionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(spnlAdoptionHistory);

        cbAge.setBackground(new java.awt.Color(255, 153, 51));
        cbAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Age", "New Born (<1 year)", "Young (1-3  year)", "Adult  (3-8 year)", "Senior (8> year)" }));

        Searchbar1.setForeground(new java.awt.Color(204, 204, 204));
        Searchbar1.setText("Jonny, parrot, husky, home-trained, kathmandu etc...");
        Searchbar1.addActionListener(this::Searchbar1ActionPerformed);

        PetFilterClear.setBackground(new java.awt.Color(255, 153, 51));
        PetFilterClear.setText("Clear");
        PetFilterClear.addActionListener(this::PetFilterClearActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblTotalAdoptedPets)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblPetCount))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Searchbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cbPetType, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbAge, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PetFilterClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pnlTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Searchbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPetType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PetFilterClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalAdoptedPets)
                    .addComponent(lblPetCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void Searchbar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchbar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Searchbar1ActionPerformed

    private void Adoption_requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adoption_requestbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adoption_requestbtnActionPerformed

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed

    }//GEN-LAST:event_Logout_btnActionPerformed

    private void profile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_btnActionPerformed

    private void PetFilterClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetFilterClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetFilterClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProviderAdoptionHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adoption_Historybtn;
    private javax.swing.JButton Adoption_requestbtn;
    private javax.swing.JButton Home_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout_btn;
    private javax.swing.JButton PetFilterClear;
    private javax.swing.JLabel Profile_text;
    private javax.swing.JTextField Searchbar1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbAge;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbPetType;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPetCount;
    private javax.swing.JLabel lblTotalAdoptedPets;
    private javax.swing.JPanel pnlTopBar;
    private javax.swing.JButton profile_btn;
    private javax.swing.JPanel spnlAdoptionHistory;
    // End of variables declaration//GEN-END:variables
}
