/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author shank
 */
public class ReportPetProvider extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportPetProvider.class.getName());

    /**
     * Creates new form ReportPetProvider
     */
    public ReportPetProvider() {
        initComponents();

    }
    
    public void addSubmitListener(ActionListener listener) {
        btnSubmit.addActionListener(listener);
    }

    public JRadioButton getRadioButton1() { return jRadioButton1; }
    public JRadioButton getRadioButton2() { return jRadioButton2; }
    public JRadioButton getRadioButton3() { return jRadioButton3; }
    public JRadioButton getRadioButton4() { return jRadioButton4; }
    public JRadioButton getRadioButton5() { return jRadioButton5; }

    public JLabel getlblShelterName()   { return lblShelterName; }
    public JLabel getlblPhoneNo_fill()  { return lblPhoneNo_fill; }
    public JLabel getlblEmail_fill()    { return lblEmail_fill; }
    public JLabel getlblAddress_fill()  { return lblAddress_fill; }
    public JLabel getShelterPfp()       { return Shelter_pfp; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Report_panel = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        lblReport = new javax.swing.JLabel();
        lblReportPfp = new javax.swing.JLabel();
        Shelter_pfp = new javax.swing.JLabel();
        lblShelterName = new javax.swing.JLabel();
        lblContacts = new javax.swing.JLabel();
        lblPhoneNo_fill = new javax.swing.JLabel();
        lblEmail_fill = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblAddress_fill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 514));
        jPanel1.setLayout(null);

        Report_panel.setBackground(new java.awt.Color(255, 255, 204));
        Report_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSubmit.setBackground(new java.awt.Color(255, 204, 102));
        btnSubmit.setText("Submit");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton1.setText("   Fake or misleading pet information");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton2.setText("   Inappropriate or suspicious behaviour");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton3.setText("   No response after adoption resquest");

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton4.setText("   Repeated incorrect or outdated listings");

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton5.setText("   Suspected scam or fraud activity");
        jRadioButton5.addActionListener(this::jRadioButton5ActionPerformed);

        lblReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReport.setText("Report");

        lblReportPfp.setBackground(new java.awt.Color(255, 255, 204));
        lblReportPfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report_icon.png"))); // NOI18N

        javax.swing.GroupLayout Report_panelLayout = new javax.swing.GroupLayout(Report_panel);
        Report_panel.setLayout(Report_panelLayout);
        Report_panelLayout.setHorizontalGroup(
            Report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Report_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(185, 185, 185))
            .addGroup(Report_panelLayout.createSequentialGroup()
                .addGroup(Report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Report_panelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(Report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton1)))
                    .addGroup(Report_panelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lblReport)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Report_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblReportPfp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Report_panelLayout.setVerticalGroup(
            Report_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Report_panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblReportPfp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReport)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addGap(48, 48, 48)
                .addComponent(btnSubmit)
                .addGap(36, 36, 36))
        );

        jPanel1.add(Report_panel);
        Report_panel.setBounds(498, 88, 452, 404);

        Shelter_pfp.setText("ShelterPfp");
        jPanel1.add(Shelter_pfp);
        Shelter_pfp.setBounds(10, 110, 70, 70);

        lblShelterName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblShelterName.setText("Shelter Name");
        jPanel1.add(lblShelterName);
        lblShelterName.setBounds(90, 130, 160, 20);

        lblContacts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContacts.setText("Contacts:");
        jPanel1.add(lblContacts);
        lblContacts.setBounds(90, 180, 60, 16);

        lblPhoneNo_fill.setText("Phone No_fill");
        jPanel1.add(lblPhoneNo_fill);
        lblPhoneNo_fill.setBounds(90, 220, 140, 16);

        lblEmail_fill.setText("Email_fill");
        jPanel1.add(lblEmail_fill);
        lblEmail_fill.setBounds(90, 250, 140, 16);

        lblLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLocation.setText("Location:");
        jPanel1.add(lblLocation);
        lblLocation.setBounds(90, 330, 60, 16);

        lblAddress_fill.setText("Address_fill");
        jPanel1.add(lblAddress_fill);
        lblAddress_fill.setBounds(90, 360, 170, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportPetProvider().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Report_panel;
    private javax.swing.JLabel Shelter_pfp;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JLabel lblAddress_fill;
    private javax.swing.JLabel lblContacts;
    private javax.swing.JLabel lblEmail_fill;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPhoneNo_fill;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblReportPfp;
    private javax.swing.JLabel lblShelterName;
    // End of variables declaration//GEN-END:variables


}
