/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author KCC
 */
public class SignupWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignupWindow.class.getName());

    /**
     * Creates new form SignupWindow
     */
    public SignupWindow() {
        initComponents();
        
        txtPassword.setEchoChar('*');
        txtConfirmPassword.setEchoChar('*');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainSignUpPanel = new javax.swing.JPanel();
        cmbRole = new javax.swing.JComboBox<>();
        LblSignUp = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        LblUsername = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        LblConfirmPassword = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        LblRole = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        PetGroupSignUp = new javax.swing.JLabel();
        cbShowPassword = new javax.swing.JCheckBox();
        RabbitSignUp = new javax.swing.JLabel();
        BirdSignUp = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        pfpMain = new javax.swing.JLabel();
        btnUploadImgMain = new javax.swing.JButton();
        btnBacktoLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainSignUpPanel.setBackground(new java.awt.Color(255, 153, 51));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adopter", "Provider" }));
        cmbRole.addActionListener(this::cmbRoleActionPerformed);

        LblSignUp.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        LblSignUp.setText("Sign Up");

        LblUsername.setText("Username:");

        LblPassword.setText("Password:");

        LblConfirmPassword.setText("Confirm Password:");

        LblEmail.setText("Email:");

        LblRole.setText("Role:");

        btnSignUp.setText("Sign In");
        btnSignUp.addActionListener(this::btnSignUpActionPerformed);

        PetGroupSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signupPetGroup.png"))); // NOI18N
        PetGroupSignUp.setText("jLabel7");

        cbShowPassword.setBackground(new java.awt.Color(255, 153, 51));
        cbShowPassword.setText("Show Password");
        cbShowPassword.addActionListener(this::cbShowPasswordActionPerformed);

        RabbitSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signUpRabbit.png"))); // NOI18N
        RabbitSignUp.setText("jLabel8");

        BirdSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signUpBird.png"))); // NOI18N
        BirdSignUp.setText("jLabel10");

        pfpMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pfp.png"))); // NOI18N
        pfpMain.setText("jLabel1");
        pfpMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pfpMain.setMaximumSize(new java.awt.Dimension(80, 80));
        pfpMain.setMinimumSize(new java.awt.Dimension(80, 80));
        pfpMain.setPreferredSize(new java.awt.Dimension(80, 80));

        btnUploadImgMain.setText("Upload Image");

        btnBacktoLogin.setText("Back to Login");

        javax.swing.GroupLayout MainSignUpPanelLayout = new javax.swing.GroupLayout(MainSignUpPanel);
        MainSignUpPanel.setLayout(MainSignUpPanelLayout);
        MainSignUpPanelLayout.setHorizontalGroup(
            MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainSignUpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblSignUp)
                .addGap(296, 296, 296)
                .addComponent(BirdSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                .addComponent(PetGroupSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblConfirmPassword))
                            .addComponent(LblPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                                .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                    .addComponent(txtEmail))
                                .addGap(15, 15, 15)
                                .addComponent(cbShowPassword))
                            .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                .addGap(120, 307, Short.MAX_VALUE))))
                    .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnUploadImgMain))
                    .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(pfpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(btnSignUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainSignUpPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBacktoLogin)
                                .addGap(113, 113, 113)))
                        .addComponent(RabbitSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MainSignUpPanelLayout.setVerticalGroup(
            MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainSignUpPanelLayout.createSequentialGroup()
                .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BirdSignUp)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainSignUpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblSignUp)
                        .addGap(38, 38, 38)
                        .addComponent(pfpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUploadImgMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainSignUpPanelLayout.createSequentialGroup()
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblRole))
                        .addGap(18, 18, 18)
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblUsername))
                        .addGap(18, 18, 18)
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPassword))
                        .addGap(18, 18, 18)
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblConfirmPassword)
                            .addComponent(cbShowPassword))
                        .addGap(18, 18, 18)
                        .addGroup(MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblEmail))
                        .addGap(18, 18, 18)
                        .addComponent(btnSignUp)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainSignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RabbitSignUp)
                        .addComponent(btnBacktoLogin))))
            .addComponent(PetGroupSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSignUpPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSignUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
        if (cbShowPassword.isSelected()) {

        txtPassword.setEchoChar((char) 0);
        txtConfirmPassword.setEchoChar((char) 0);

    } else {

        txtPassword.setEchoChar('*');
        txtConfirmPassword.setEchoChar('*');
    }
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    
    // listener for SignUp button of main signup window
    public void addSignupListener(ActionListener listener) {
        btnSignUp.addActionListener(listener);
    }
    
    // Getting text field data
    public javax.swing.JTextField getTxtUsername() {
        return txtUsername;
    }

    public javax.swing.JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public javax.swing.JPasswordField getTxtConfirmPassword() {
        return txtConfirmPassword;
    }

    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    public javax.swing.JComboBox<String> getCmbRole() {
        return cmbRole;
    }
    
    
    
    // Listener method for Upload Image button action call
    public void addUploadImageListener(ActionListener listener) {
       btnUploadImgMain.addActionListener(listener);
    }
    
    // returning the uploaded image
    public javax.swing.JLabel getPfpMain() {
        return pfpMain;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignupWindow().setVisible(true));
    }
    
    
    // listener for Back to Login button
    public void addBackToLoginListener(ActionListener listener) {
        btnBacktoLogin.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BirdSignUp;
    private javax.swing.JLabel LblConfirmPassword;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblRole;
    private javax.swing.JLabel LblSignUp;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JPanel MainSignUpPanel;
    private javax.swing.JLabel PetGroupSignUp;
    private javax.swing.JLabel RabbitSignUp;
    private javax.swing.JButton btnBacktoLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnUploadImgMain;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel pfpMain;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
